var localization = {
'English': {
	'title1': 'Aleph with Beth and Alpha with Angela', 
	'title2': 'Learning Scheduler', 
	'language': 'Language',
	'Learning program': 'Learning program', 
	'timePerDay': 'Time per day', 
	'load': 'Load', 
	'print': 'Print', 
	'Aleph': 'Aleph with Beth', 
	'Alpha': 'Alpha with Angela', 
	'english': 'English', 
	'french': 'French', 
	'portuguese': 'Portuguese', 
	'spanish': 'Spanish'
	},
'French': {
	'title1': 'Aleph avec Beth et Alpha avec Angela', 
	'title2': 'Apprentissage du planificateur', 
	'language': 'Langue',
	'Learning program': 'Programme d’apprentissage', 
	'timePerDay': 'Temps par jour', 
	'load': 'Charger', 
	'print': 'Imprimer', 
	'Aleph': 'Aleph avec Beth', 
	'Alpha': 'Alpha avec Angela', 
	'english': 'Anglais', 
	'french': 'Français', 
	'portuguese': 'Portugais', 
	'spanish': 'Espagnol'
	},
'Portuguese': {
	'title1': 'Aleph com Beth e Alpha com Angela', 
	'title2': 'Programador de aprendizagem', 
	'language': 'Idioma',
	'Learning program': 'Programa de aprendizagem', 
	'timePerDay': 'tempo por dia', 
	'load': 'Carga', 
	'print': 'Impressão', 
	'Aleph': 'Aleph com Beth', 
	'Alpha': 'Alpha com Angela', 
	'english': 'Inglês', 
	'french': 'Francês', 
	'portuguese': 'Português', 
	'spanish': 'Espanhol'
	},
'Spanish': {
	'title1': 'Aleph con Beth y Alpha con Angela', 
	'title2': 'Programador de aprendizaje', 
	'language': 'Idioma',
	'Learning program': 'Programa de aprendizaje', 
	'timePerDay': 'Tiempo por día', 
	'load': 'Carga', 
	'print': 'Impresión', 
	'Aleph': 'Aleph con Beth', 
	'Alpha': 'Alpha con Angela', 
	'english': 'Inglés', 
	'french': 'Francés', 
	'portuguese': 'Portugués', 
	'spanish': 'Español'
	},
};