var localization = {
'Afrikaans': {
	'title1': 'Aleph met Beth en Alpha met Angela',
	'title2': 'Leerskeduleerder',
	'language': 'Taal',
	'Learning program': 'Leerprogram',
	'timePerDay': 'Tyd per dag',
	'copy': 'Kopieer',
	'copied': 'Gekopieer',
	'print': 'Druk',
	'Aleph': 'Aleph saam met Beth',
	'Alpha': 'Alfa met Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albanees',
	'amharic': 'Amharies',
	'arabic': 'Arabies',
	'assamese': 'Assamees',
	'bengali': 'Bengaals',
	'burmese': 'Birmaanse',
	'cebuano': 'Cebuano',
	'croatian': 'Kroaties',
	'dutch': 'Nederlands',
	'english': 'Engels',
	'farsi': 'Farsi',
	'finnish': 'Fins',
	'french': 'Frans',
	'fulfulde': 'Volvolle',
	'german': 'Duits',
	'greek': 'Grieks',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebreeus',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hongaars',
	'iloko': 'Iloko',
	'indonesian': 'Indonesies',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Koreaans',
	'lao': 'Lao',
	'malagasy': 'Malgassies',
	'malay': 'Maleis',
	'malayalam': 'Malabaars',
	'mandarin': 'Mandaryns',
	'marathi': 'Marathi',
	'nepali': 'Nepalees',
	'odia': 'Odia',
	'pashto': 'Pasjto',
	'polish': 'Pools',
	'portuguese': 'Portugees',
	'punjabi': 'Punjabi',
	'russian': 'Russies',
	'serbian': 'Serwies',
	'sindhi': 'Sindhi',
	'spanish': 'Spaans',
	'swahili': 'Swahili',
	'swedish': 'Sweeds',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turks',
	'vietnamese': 'Viëtnamees',
	'urdu': 'Oerdoe',
	'direction': '',
	'font': '',
	},
'Albanian': {
	'title1': 'Alefi me Bethin dhe Alfa me Anxhelen',
	'title2': 'Programuesi i mësimit',
	'language': 'Gjuha',
	'Learning program': 'Programi mësimor',
	'timePerDay': 'Koha në ditë',
	'copy': 'Kopjo',
	'copied': 'E kopjuar',
	'print': 'Printo',
	'Aleph': 'Alefi me Bethin',
	'Alpha': 'Alfa me Anxhelen',
	'afrikaans': 'afrikane',
	'albanian': 'shqiptare',
	'amharic': 'amharike',
	'arabic': 'arabisht',
	'assamese': 'asamez',
	'bengali': 'Bengalisht',
	'burmese': 'birmaneze',
	'cebuano': 'Cebuano',
	'croatian': 'kroate',
	'dutch': 'holandeze',
	'english': 'anglisht',
	'farsi': 'persisht',
	'finnish': 'finlandez',
	'french': 'frëngjisht',
	'fulfulde': 'Fulfulde',
	'german': 'gjermanisht',
	'greek': 'greke',
	'gujarati': 'guxharatisht',
	'hausa': 'Hausa',
	'hebrew': 'hebraishtja',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'hungareze',
	'iloko': 'Iloko',
	'indonesian': 'indonezisht',
	'kannada': 'kanadeze',
	'khmer': 'Khmer',
	'korean': 'koreane',
	'lao': 'Lao',
	'malagasy': 'Malagazi',
	'malay': 'Malay',
	'malayalam': 'malajalamisht',
	'mandarin': 'Mandarina',
	'marathi': 'Marathi',
	'nepali': 'nepalisht',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'polonisht',
	'portuguese': 'portugeze',
	'punjabi': 'Punjabi',
	'russian': 'rusisht',
	'serbian': 'serb',
	'sindhi': 'Sindhi',
	'spanish': 'spanjisht',
	'swahili': 'Suahili',
	'swedish': 'suedeze',
	'tagalog': 'Tagalogisht',
	'tamil': 'tamile',
	'telugu': 'telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turqisht',
	'vietnamese': 'vietnameze',
	'urdu': 'urdu',
	'direction': '',
	'font': '',
	},
'Amharic': {
	'title1': 'አሌፍ ከቤቴ እና ከአንጀላ ጋር አልፋ',
	'title2': 'የመማሪያ መርሐግብር',
	'language': 'ቋንቋ',
	'Learning program': 'የመማሪያ ፕሮግራም',
	'timePerDay': 'ጊዜ በቀን',
	'copy': 'ቅዳ',
	'copied': 'ተገልብጧል',
	'print': 'አትም',
	'Aleph': 'አሌፍ ከቤት ጋር',
	'Alpha': 'አልፋ ከአንጀላ ጋር',
	'afrikaans': 'አፍሪካንስ',
	'albanian': 'አልበንያኛ',
	'amharic': 'አማርኛ',
	'arabic': 'አረብኛ',
	'assamese': 'አሳሜሴ',
	'bengali': 'ቤንጋሊ',
	'burmese': 'በርሚስ',
	'cebuano': 'ሴቡአኖ',
	'croatian': 'ክሮኤሽያን',
	'dutch': 'ደች',
	'english': 'እንግሊዝኛ',
	'farsi': 'ፋርሲ',
	'finnish': 'ፊኒሽ',
	'french': 'ፈረንሳይኛ',
	'fulfulde': 'ፉልፉልዴ',
	'german': 'ጀርመንኛ',
	'greek': 'ግሪክኛ',
	'gujarati': 'ጉጅራቲ',
	'hausa': 'ሃውሳ',
	'hebrew': 'ሂብሩ',
	'hindi': 'ሂንዲ',
	'hmong': 'ሕሞንግ',
	'hungarian': 'ሃንጋሪያን',
	'iloko': 'ኢሎኮ',
	'indonesian': 'ኢንዶኔዥያን',
	'kannada': 'ካናዳ',
	'khmer': 'ክመር',
	'korean': 'ኮሪያኛ',
	'lao': 'ላኦ',
	'malagasy': 'ማላጋሲያ',
	'malay': 'ማላይ',
	'malayalam': 'ማላያላም',
	'mandarin': 'ማንዳሪን',
	'marathi': 'ማራቲ',
	'nepali': 'ኔፓሊ',
	'odia': 'ኦዲያ',
	'pashto': 'ፓሽቶ',
	'polish': 'ፖሊሽ',
	'portuguese': 'ፖርቹጋልኛ',
	'punjabi': 'ፑንጃቢ',
	'russian': 'ራሺያኛ',
	'serbian': 'ሰሪቢያን',
	'sindhi': 'ስንድሂ',
	'spanish': 'ስፓንኛ',
	'swahili': 'ስዋሕሊ',
	'swedish': 'ስዊድንኛ',
	'tagalog': 'ታንጋሎግ',
	'tamil': 'ታሚል',
	'telugu': 'ተሉጉ',
	'thai': 'ታይ',
	'tok pisin': 'ቶክ ፒሲን',
	'turkish': 'ቱሪክሽ',
	'vietnamese': 'ቪትናሜሴ',
	'urdu': 'ኡርዱ',
	'direction': '',
	'font': '',
	},
'Arabic': {
	'title1': 'ألف مع بيث وألفا مع أنجيلا',
	'title2': 'جدول التعلم',
	'language': 'لغة',
	'Learning program': 'برنامج التعلم',
	'timePerDay': 'الوقت في اليوم',
	'copy': 'ينسخ',
	'copied': 'تم نسخها',
	'print': 'مطبعة',
	'Aleph': 'ألف مع بيث',
	'Alpha': 'ألفا مع أنجيلا',
	'afrikaans': 'الأفريكانية',
	'albanian': 'الألبانية',
	'amharic': 'الأمهرية',
	'arabic': 'عربي',
	'assamese': 'الآسامية',
	'bengali': 'البنغالية',
	'burmese': 'البورمية',
	'cebuano': 'سيبوانو',
	'croatian': 'الكرواتية',
	'dutch': 'هولندي',
	'english': 'إنجليزي',
	'farsi': 'الفارسية',
	'finnish': 'الفنلندية',
	'french': 'فرنسي',
	'fulfulde': 'فولفولدي',
	'german': 'الألمانية',
	'greek': 'اليونانية',
	'gujarati': 'الغوجاراتية',
	'hausa': 'الهاوسا',
	'hebrew': 'العبرية',
	'hindi': 'الهندية',
	'hmong': 'همونغ',
	'hungarian': 'المجرية',
	'iloko': 'إيلوكو',
	'indonesian': 'اللغة الإندونيسية',
	'kannada': 'كانادا',
	'khmer': 'الخميرية',
	'korean': 'كوري',
	'lao': 'لاو',
	'malagasy': 'اللغة الملغاشية',
	'malay': 'الملايو',
	'malayalam': 'المالايالامية',
	'mandarin': 'الماندرين',
	'marathi': 'الماراثى',
	'nepali': 'النيبالية',
	'odia': 'أوديا',
	'pashto': 'البشتونية',
	'polish': 'بولندي',
	'portuguese': 'البرتغالية',
	'punjabi': 'البنجابية',
	'russian': 'الروسية',
	'serbian': 'الصربية',
	'sindhi': 'السندية',
	'spanish': 'الأسبانية',
	'swahili': 'السواحلية',
	'swedish': 'السويدية',
	'tagalog': 'التاغالوغية',
	'tamil': 'التاميلية',
	'telugu': 'التيلجو',
	'thai': 'تايلاندي',
	'tok pisin': 'توك بيسين',
	'turkish': 'اللغة التركية',
	'vietnamese': 'الفيتنامية',
	'urdu': 'الأردية',
	'direction': 'RTL',
	'font': 'Arial',
	},
'Assamese': {
	'title1': 'বেথৰ সৈতে আলেফ আৰু এঞ্জেলাৰ সৈতে আলফা',
	'title2': 'শিক্ষণ সময়সূচী',
	'language': 'ভাষা',
	'Learning program': 'শিক্ষণ কাৰ্যসূচী',
	'timePerDay': 'প্ৰতিদিনে সময়',
	'copy': 'কপি কৰক',
	'copied': 'কপি কৰা হৈছে',
	'print': 'প্ৰিন্ট কৰক',
	'Aleph': 'বেথৰ সৈতে আলেফ',
	'Alpha': 'এঞ্জেলাৰ সৈতে আলফা',
	'afrikaans': 'আফ্ৰিকান ভাষা',
	'albanian': 'আলবেনিয়ান',
	'amharic': 'আমহাৰিক',
	'arabic': 'আৰবী',
	'assamese': 'অসমীয়া',
	'bengali': 'বাংলা',
	'burmese': 'বাৰ্মিজ',
	'cebuano': 'চেবুয়ানো',
	'croatian': 'ক্ৰ\'ৱেচিয়ান',
	'dutch': 'ডাচ্চ',
	'english': 'ইংৰাজী',
	'farsi': 'ফাৰ্চী',
	'finnish': 'ফিনিছ',
	'french': 'ফৰাচী',
	'fulfulde': 'ফুলফুল্দে',
	'german': 'জাৰ্মান',
	'greek': 'গ্ৰীক',
	'gujarati': 'গুজৰাটী',
	'hausa': 'হাউছা',
	'hebrew': 'হিব্ৰু',
	'hindi': 'হিন্দী',
	'hmong': 'হমং',
	'hungarian': 'হাংগেৰী',
	'iloko': 'ইলোকো',
	'indonesian': 'ইণ্ডোনেছিয়ান',
	'kannada': 'কানাড়া ভাষা',
	'khmer': 'খ্মেৰ',
	'korean': 'কোৰিয়ান',
	'lao': 'লাও',
	'malagasy': 'মালাগাছি',
	'malay': 'মালয়',
	'malayalam': 'মালয়ালম',
	'mandarin': 'মেণ্ডেৰিন',
	'marathi': 'মাৰাঠী',
	'nepali': 'নেপালী',
	'odia': 'ওডিয়া',
	'pashto': 'পাষ্টো',
	'polish': 'পোলিছ',
	'portuguese': 'পৰ্তুগীজ',
	'punjabi': 'পাঞ্জাবী',
	'russian': 'ৰাছিয়ান',
	'serbian': 'ছাৰ্বিয়ান',
	'sindhi': 'সিন্ধী',
	'spanish': 'স্পেনিছ',
	'swahili': 'শ্বাহিলী',
	'swedish': 'ছুইডিছ',
	'tagalog': 'টাগালগ',
	'tamil': 'তামিল',
	'telugu': 'তেলেগু',
	'thai': 'থাই ভাষা',
	'tok pisin': 'টক পিচিন',
	'turkish': 'তুৰ্কী ভাষা',
	'vietnamese': 'ভিয়েটনামী',
	'urdu': 'উৰ্দু',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Bengali': {
	'title1': 'বেথের সাথে আলেফ এবং অ্যাঞ্জেলার সাথে আলফা',
	'title2': 'শেখার সময়সূচী',
	'language': 'ভাষা',
	'Learning program': 'শেখার প্রোগ্রাম',
	'timePerDay': 'প্রতিদিন সময়',
	'copy': 'কপি',
	'copied': 'কপি করা হয়েছে',
	'print': 'ছাপা',
	'Aleph': 'বেথের সাথে আলেফ',
	'Alpha': 'অ্যাঞ্জেলার সাথে আলফা',
	'afrikaans': 'আফ্রিকান্স',
	'albanian': 'আলবেনীয়',
	'amharic': 'আমহারিক',
	'arabic': 'আরবি',
	'assamese': 'অসমীয়া',
	'bengali': 'বাংলা',
	'burmese': 'বার্মিজ',
	'cebuano': 'সেবুয়ানো',
	'croatian': 'ক্রোয়েশিয়ান',
	'dutch': 'ডাচ',
	'english': 'ইংরেজী',
	'farsi': 'ফার্সি',
	'finnish': 'ফিনিশ',
	'french': 'ফরাসি',
	'fulfulde': 'ফুলফুলদে',
	'german': 'জার্মান',
	'greek': 'গ্রীক',
	'gujarati': 'গুজরাটি',
	'hausa': 'হাউসা',
	'hebrew': 'হিব্রু',
	'hindi': 'হিন্দি',
	'hmong': 'হ্মং',
	'hungarian': 'হাঙ্গেরীয়',
	'iloko': 'ইলোকো',
	'indonesian': 'ইন্দোনেশীয়',
	'kannada': 'কন্নড়',
	'khmer': 'খেমার',
	'korean': 'কোরিয়ান',
	'lao': 'লাও',
	'malagasy': 'মালাগাসি',
	'malay': 'মালে',
	'malayalam': 'মালায়ালাম',
	'mandarin': 'ম্যান্ডারিন',
	'marathi': 'মারাঠি',
	'nepali': 'নেপালি',
	'odia': 'ওড়িয়া',
	'pashto': 'পশতু',
	'polish': 'পোলীশ',
	'portuguese': 'পর্তুগীজ',
	'punjabi': 'পাঞ্জাবি',
	'russian': 'রুশ',
	'serbian': 'সার্বীয়',
	'sindhi': 'সিন্ধি',
	'spanish': 'স্পেনীয়',
	'swahili': 'সোয়াহিলি',
	'swedish': 'সুইডিশ',
	'tagalog': 'তাগালগ',
	'tamil': 'তামিল',
	'telugu': 'তেলেগু',
	'thai': 'থাই',
	'tok pisin': 'টোক পিসিন',
	'turkish': 'তুর্কী',
	'vietnamese': 'ভিয়েতনামী',
	'urdu': 'উর্দু',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Burmese': {
	'title1': 'Aleph နှင့်အတူ Beth နှင့် Alpha နှင့် Angela',
	'title2': 'သင်ယူမှုအချိန်ဇယား',
	'language': 'ဘာသာစကား',
	'Learning program': 'သင်ယူမှုအစီအစဉ်',
	'timePerDay': 'တစ်နေ့လျှင် အချိန်',
	'copy': 'ကော်ပီ',
	'copied': 'ကူးယူသည်။',
	'print': 'ညောင်ပင်',
	'Aleph': 'Aleph နဲ့ Beth ပါ။',
	'Alpha': 'Angela နှင့် Alpha',
	'afrikaans': 'အာဖရိကန်',
	'albanian': 'အယ်လ်ဘေးနီးယန်း',
	'amharic': 'Amharic',
	'arabic': 'အာရဗီ',
	'assamese': 'အာသံ',
	'bengali': 'ဘင်္ဂါလီ',
	'burmese': 'မြန်မာ',
	'cebuano': 'စီဘူနို',
	'croatian': 'ခရိုအေးရှား',
	'dutch': 'ဒတ်ခ်ျ',
	'english': 'အင်္ဂလိပ်စာ',
	'farsi': 'ဖာစီ',
	'finnish': 'ဖင်',
	'french': 'ပြင်သစ်',
	'fulfulde': 'ဖူလ်ဒီ',
	'german': 'ဂျာမန်',
	'greek': 'ဂရိ',
	'gujarati': 'ဂူဂျာရတ်',
	'hausa': 'Hausa',
	'hebrew': 'ဟီး',
	'hindi': 'ဟိန္ဒီ',
	'hmong': 'မုံ',
	'hungarian': 'ဟန်ဂေရီ',
	'iloko': 'Iloko',
	'indonesian': 'အင်ဒိုနီးရှား',
	'kannada': 'ကန်နာဒါ',
	'khmer': 'ခမာ',
	'korean': 'ကိုးရီးယား',
	'lao': 'လာအို',
	'malagasy': 'အာလာဂါစီ',
	'malay': 'မလေး',
	'malayalam': 'မလေး',
	'mandarin': 'မန်ဒရင်း',
	'marathi': 'မာရသီ',
	'nepali': 'နီပေါ',
	'odia': 'အိုဒီးယား',
	'pashto': 'ပါရှတို',
	'polish': 'ပိုလန်',
	'portuguese': 'ပေါ်တူဂီ',
	'punjabi': 'ပန်ချာပီ',
	'russian': 'ရုရှ',
	'serbian': 'ဆားဘီးယား',
	'sindhi': 'ဒြီ',
	'spanish': 'ငပိ',
	'swahili': 'ဆွာဟီလီ',
	'swedish': 'ဒိ',
	'tagalog': 'တဂါလော့',
	'tamil': 'တမီလ်',
	'telugu': 'အဂု',
	'thai': 'ထိုင်း',
	'tok pisin': 'Tok Pisin',
	'turkish': 'တူရကီ',
	'vietnamese': 'ဗီယက်နမ်',
	'urdu': 'အူရဒူ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Cebuano': {
	'title1': 'Si Aleph uban ni Beth ug si Alpha uban ni Angela',
	'title2': 'Pag-iskedyul sa pagkat-on',
	'language': 'Pinulongan',
	'Learning program': 'Programa sa pagkat-on',
	'timePerDay': 'Oras kada adlaw',
	'copy': 'Kopyaha',
	'copied': 'Gikopya',
	'print': 'Iimprinta',
	'Aleph': 'Si Aleph uban ni Beth',
	'Alpha': 'Alpha kauban si Angela',
	'afrikaans': 'Aprikaans',
	'albanian': 'Albaniano',
	'amharic': 'Amharic',
	'arabic': 'Arabiko',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese',
	'cebuano': 'Cebuano',
	'croatian': 'Croatiano',
	'dutch': 'Dutch',
	'english': 'English',
	'farsi': 'Farsi',
	'finnish': 'Finnish',
	'french': 'Pranses',
	'fulfulde': 'Fulfulde',
	'german': 'Aleman',
	'greek': 'Griyego',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebreohanon',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hungarian',
	'iloko': 'Iloko',
	'indonesian': 'Indonesian',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Koreano',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polish',
	'portuguese': 'Portuges',
	'punjabi': 'Punjabi',
	'russian': 'Ruso',
	'serbian': 'Serbiano',
	'sindhi': 'Sindhi',
	'spanish': 'Kinatsila',
	'swahili': 'Swahili',
	'swedish': 'Swedish',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turko',
	'vietnamese': 'Vietnamese',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Croatian': {
	'title1': 'Aleph s Beth i Alpha s Angelom',
	'title2': 'Planer učenja',
	'language': 'Jezik',
	'Learning program': 'Program učenja',
	'timePerDay': 'Vrijeme dnevno',
	'copy': 'Kopirati',
	'copied': 'Kopirano',
	'print': 'Ispis',
	'Aleph': 'Aleph s Beth',
	'Alpha': 'Alfa s Angelom',
	'afrikaans': 'afrikaans',
	'albanian': 'albanski',
	'amharic': 'amharski',
	'arabic': 'arapski',
	'assamese': 'asamski',
	'bengali': 'bengalski',
	'burmese': 'burmanski',
	'cebuano': 'Cebuano',
	'croatian': 'hrvatski',
	'dutch': 'nizozemski',
	'english': 'engleski',
	'farsi': 'farsi',
	'finnish': 'finski',
	'french': 'francuski',
	'fulfulde': 'Fulfulde',
	'german': 'njemački',
	'greek': 'grčki',
	'gujarati': 'gudžarati',
	'hausa': 'hausa',
	'hebrew': 'hebrejski',
	'hindi': 'hindski',
	'hmong': 'Hmong',
	'hungarian': 'mađarski',
	'iloko': 'Iloko',
	'indonesian': 'indonezijski',
	'kannada': 'kannada',
	'khmer': 'kmerski',
	'korean': 'korejski',
	'lao': 'Lao',
	'malagasy': 'malgaški',
	'malay': 'malajski',
	'malayalam': 'malajalamski',
	'mandarin': 'Mandarinski',
	'marathi': 'marati',
	'nepali': 'nepalski',
	'odia': 'Odia',
	'pashto': 'paštunski',
	'polish': 'Polirati',
	'portuguese': 'portugalski',
	'punjabi': 'pandžapski',
	'russian': 'ruski',
	'serbian': 'srpski',
	'sindhi': 'sindhi',
	'spanish': 'španjolski',
	'swahili': 'svahili',
	'swedish': 'švedski',
	'tagalog': 'tagalog',
	'tamil': 'Tamil',
	'telugu': 'teluški',
	'thai': 'tajlandski',
	'tok pisin': 'tok pisin',
	'turkish': 'turski',
	'vietnamese': 'vijetnamski',
	'urdu': 'urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Dutch': {
	'title1': 'Aleph met Beth en Alpha met Angela',
	'title2': 'Leerplanner',
	'language': 'Taal',
	'Learning program': 'Leerprogramma',
	'timePerDay': 'Tijd per dag',
	'copy': 'Kopiëren',
	'copied': 'Gekopieerd',
	'print': 'Afdrukken',
	'Aleph': 'Aleph met Beth',
	'Alpha': 'Alpha met Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albanees',
	'amharic': 'Amhaars',
	'arabic': 'Arabisch',
	'assamese': 'Assamees',
	'bengali': 'Bengaals',
	'burmese': 'Birmees',
	'cebuano': 'Cebuaans',
	'croatian': 'Kroatisch',
	'dutch': 'Nederlands',
	'english': 'Engels',
	'farsi': 'Perzisch',
	'finnish': 'Fins',
	'french': 'Frans',
	'fulfulde': 'Vervuld',
	'german': 'Duits',
	'greek': 'Grieks',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebreeuws',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hongaars',
	'iloko': 'Iloko',
	'indonesian': 'Indonesisch',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Koreaans',
	'lao': 'Laotiaans',
	'malagasy': 'Madagaskar',
	'malay': 'Maleis',
	'malayalam': 'Maleis',
	'mandarin': 'Mandarijn',
	'marathi': 'Marathi',
	'nepali': 'Nepalees',
	'odia': 'Odia',
	'pashto': 'Pasjtoe',
	'polish': 'Pools',
	'portuguese': 'Portugees',
	'punjabi': 'Punjabi',
	'russian': 'Russisch',
	'serbian': 'Servisch',
	'sindhi': 'Sindhi',
	'spanish': 'Spaans',
	'swahili': 'Swahili',
	'swedish': 'Zweeds',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thais',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turks',
	'vietnamese': 'Vietnamees',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'English': {
	'title1': 'Aleph with Beth and Alpha with Angela',
	'title2': 'Learning Scheduler',
	'language': 'Language',
	'Learning program': 'Learning program',
	'timePerDay': 'Time per day',
	'copy': 'Copy',
	'copied': 'Copied',
	'print': 'Print',
	'Aleph': 'Aleph with Beth',
	'Alpha': 'Alpha with Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albanian',
	'amharic': 'Amharic',
	'arabic': 'Arabic',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese',
	'cebuano': 'Cebuano',
	'croatian': 'Croatian',
	'dutch': 'Dutch',
	'english': 'English',
	'farsi': 'Farsi',
	'finnish': 'Finnish',
	'french': 'French',
	'fulfulde': 'Fulfulde',
	'german': 'German',
	'greek': 'Greek',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebrew',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hungarian',
	'iloko': 'Iloko',
	'indonesian': 'Indonesian',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Korean',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polish',
	'portuguese': 'Portuguese',
	'punjabi': 'Punjabi',
	'russian': 'Russian',
	'serbian': 'Serbian',
	'sindhi': 'Sindhi',
	'spanish': 'Spanish',
	'swahili': 'Swahili',
	'swedish': 'Swedish',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turkish',
	'vietnamese': 'Vietnamese',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Farsi': {
	'title1': 'الف با بث و آلفا با آنجلا',
	'title2': 'زمانبندی یادگیری',
	'language': 'زبان',
	'Learning program': 'برنامه یادگیری',
	'timePerDay': 'زمان در روز',
	'copy': 'کپی کنید',
	'copied': 'کپی شده است',
	'print': 'چاپ کنید',
	'Aleph': 'الف با بث',
	'Alpha': 'آلفا با آنجلا',
	'afrikaans': 'آفریقایی',
	'albanian': 'آلبانیایی',
	'amharic': 'آمهری',
	'arabic': 'عربی',
	'assamese': 'آسامی',
	'bengali': 'بنگالی',
	'burmese': 'برمه ای',
	'cebuano': 'سبوانو',
	'croatian': 'کروات',
	'dutch': 'هلندی',
	'english': 'انگلیسی',
	'farsi': 'فارسی',
	'finnish': 'فنلاندی',
	'french': 'فرانسوی',
	'fulfulde': 'فولفولد',
	'german': 'آلمانی',
	'greek': 'یونانی',
	'gujarati': 'گجراتی',
	'hausa': 'هاوسا',
	'hebrew': 'عبری',
	'hindi': 'هندی',
	'hmong': 'همونگ',
	'hungarian': 'مجارستانی',
	'iloko': 'ایلوکو',
	'indonesian': 'اندونزیایی',
	'kannada': 'کانادا',
	'khmer': 'خمر',
	'korean': 'کره ای',
	'lao': 'لائوس',
	'malagasy': 'مالاگاسی',
	'malay': 'مالایی',
	'malayalam': 'مالایایی',
	'mandarin': 'ماندارین',
	'marathi': 'مراتی',
	'nepali': 'نپالی',
	'odia': 'اودیا',
	'pashto': 'پشتو',
	'polish': 'لهستانی',
	'portuguese': 'پرتغالی',
	'punjabi': 'پنجابی',
	'russian': 'روسی',
	'serbian': 'صربی',
	'sindhi': 'سندی',
	'spanish': 'اسپانیایی',
	'swahili': 'سواحیلی',
	'swedish': 'سوئدی',
	'tagalog': 'تاگالوگ',
	'tamil': 'تامیل',
	'telugu': 'تلوگو',
	'thai': 'تایلندی',
	'tok pisin': 'توک پیسین',
	'turkish': 'ترکی',
	'vietnamese': 'ویتنامی',
	'urdu': 'اردو',
	'direction': 'RTL',
	'font': 'Arial',
	},
'Finnish': {
	'title1': 'Aleph Bethin kanssa ja Alfa Angelan kanssa',
	'title2': 'Oppimisaikataulu',
	'language': 'Kieli',
	'Learning program': 'Oppimisohjelma',
	'timePerDay': 'Aikaa päivässä',
	'copy': 'Kopioida',
	'copied': 'Kopioitu',
	'print': 'Painaa',
	'Aleph': 'Aleph Bethin kanssa',
	'Alpha': 'Alfa Angelan kanssa',
	'afrikaans': 'afrikaans',
	'albanian': 'albanialainen',
	'amharic': 'amhara',
	'arabic': 'arabia',
	'assamese': 'Assami',
	'bengali': 'bengali',
	'burmese': 'burmalainen',
	'cebuano': 'Cebuano',
	'croatian': 'kroatialainen',
	'dutch': 'hollantilainen',
	'english': 'englanti',
	'farsi': 'farsi',
	'finnish': 'suomalainen',
	'french': 'ranskalainen',
	'fulfulde': 'Fullfulde',
	'german': 'saksaksi',
	'greek': 'kreikkalainen',
	'gujarati': 'gudžarati',
	'hausa': 'Hausa',
	'hebrew': 'heprealainen',
	'hindi': 'hindi',
	'hmong': 'hmong',
	'hungarian': 'Unkari',
	'iloko': 'Iloko',
	'indonesian': 'Indonesialainen',
	'kannada': 'kannada',
	'khmer': 'khmerit',
	'korean': 'korealainen',
	'lao': 'Lao',
	'malagasy': 'Madagaskari',
	'malay': 'malaiji',
	'malayalam': 'malajalami',
	'mandarin': 'Mandariini',
	'marathi': 'marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'pashto',
	'polish': 'Kiillottaa',
	'portuguese': 'portugali',
	'punjabi': 'Punjabi',
	'russian': 'venäjäksi',
	'serbian': 'serbia',
	'sindhi': 'Sindhi',
	'spanish': 'espanja',
	'swahili': 'swahili',
	'swedish': 'ruotsinkielinen',
	'tagalog': 'Tagalog',
	'tamil': 'tamili',
	'telugu': 'telugu',
	'thai': 'thaimaalainen',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turkkilainen',
	'vietnamese': 'vietnam',
	'urdu': 'urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'French': {
	'title1': 'Aleph avec Beth et Alpha avec Angela',
	'title2': 'Planificateur d\'apprentissage',
	'language': 'Langue',
	'Learning program': 'Programme d\'apprentissage',
	'timePerDay': 'Heure par jour',
	'copy': 'Copie',
	'copied': 'Copié',
	'print': 'Imprimer',
	'Aleph': 'Aleph avec Beth',
	'Alpha': 'Alpha avec Angela',
	'afrikaans': 'afrikaans',
	'albanian': 'albanais',
	'amharic': 'amharique',
	'arabic': 'arabe',
	'assamese': 'Assamais',
	'bengali': 'bengali',
	'burmese': 'birman',
	'cebuano': 'Cebuano',
	'croatian': 'croate',
	'dutch': 'Néerlandais',
	'english': 'Anglais',
	'farsi': 'Farsi',
	'finnish': 'finlandais',
	'french': 'Français',
	'fulfulde': 'Fulfulde',
	'german': 'Allemand',
	'greek': 'grec',
	'gujarati': 'Gujarati',
	'hausa': 'Haoussa',
	'hebrew': 'hébreu',
	'hindi': 'hindi',
	'hmong': 'Hmong',
	'hungarian': 'hongrois',
	'iloko': 'Iloko',
	'indonesian': 'indonésien',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'coréen',
	'lao': 'Lao',
	'malagasy': 'malgache',
	'malay': 'malais',
	'malayalam': 'Malayalam',
	'mandarin': 'mandarin',
	'marathi': 'Marathi',
	'nepali': 'Népalais',
	'odia': 'Odia',
	'pashto': 'Pachtoune',
	'polish': 'polonais',
	'portuguese': 'portugais',
	'punjabi': 'Pendjabi',
	'russian': 'russe',
	'serbian': 'serbe',
	'sindhi': 'Sindhi',
	'spanish': 'Espagnol',
	'swahili': 'Swahili',
	'swedish': 'suédois',
	'tagalog': 'Tagalog',
	'tamil': 'Tamoul',
	'telugu': 'Télougou',
	'thai': 'thaïlandais',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turc',
	'vietnamese': 'vietnamien',
	'urdu': 'Ourdou',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Fulfulde': {
	'title1': 'Alef e Bet e Alfa e Angela',
	'title2': 'Jaɓɓoowo janngugol',
	'language': 'Wolde',
	'Learning program': 'Porogaraam janngugol',
	'timePerDay': 'Waktu e ñalawma',
	'copy': 'Koppir',
	'copied': 'Koppiraama',
	'print': 'Tappirde',
	'Aleph': 'Alef e Beet',
	'Alpha': 'Alfa e Angela',
	'afrikaans': 'Afriknaajo',
	'albanian': 'Albaani',
	'amharic': 'Amhariyanke',
	'arabic': 'Arab',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Birmaani',
	'cebuano': 'Sebunaajo',
	'croatian': 'Korowasi',
	'dutch': 'Holanndeejo',
	'english': 'Inglisia',
	'farsi': 'Farsi',
	'finnish': 'Finlande',
	'french': 'Farayse',
	'fulfulde': 'Fulfulde',
	'german': 'Almaañnaajo',
	'greek': 'Gerek',
	'gujarati': 'Gujarat',
	'hausa': 'Hawsa',
	'hebrew': 'Ebere',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Honngiri',
	'iloko': 'Iloko',
	'indonesian': 'Indoneesi',
	'kannada': 'Kannaada',
	'khmer': 'Kmer',
	'korean': 'Koreeji',
	'lao': 'Lao',
	'malagasy': 'Malagasi',
	'malay': 'Malawi',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Maratiri',
	'nepali': 'Nepaali',
	'odia': 'Odiya',
	'pashto': 'Pashto',
	'polish': 'Poloñ',
	'portuguese': 'Purtugeec',
	'punjabi': 'Punjaabi',
	'russian': 'Riisi',
	'serbian': 'Serbi',
	'sindhi': 'Sinndi',
	'spanish': 'Espanis',
	'swahili': 'Suwahili',
	'swedish': 'Suwednaajo',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Taylande',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turki',
	'vietnamese': 'Wiyetnaamnaaɓe',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'German': {
	'title1': 'Aleph mit Beth und Alpha mit Angela',
	'title2': 'Lernplaner',
	'language': 'Sprache',
	'Learning program': 'Lernprogramm',
	'timePerDay': 'Zeit pro Tag',
	'copy': 'Kopie',
	'copied': 'Kopiert',
	'print': 'Drucken',
	'Aleph': 'Aleph mit Beth',
	'Alpha': 'Alpha mit Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'albanisch',
	'amharic': 'Birmanisch',
	'arabic': 'Arabisch',
	'assamese': 'Assamesisch',
	'bengali': 'Bengali',
	'burmese': 'birmanisch',
	'cebuano': 'Cebuano',
	'croatian': 'kroatisch',
	'dutch': 'Niederländisch',
	'english': 'Englisch',
	'farsi': 'Persisch',
	'finnish': 'finnisch',
	'french': 'Französisch',
	'fulfulde': 'Fulfulde',
	'german': 'Deutsch',
	'greek': 'griechisch',
	'gujarati': 'Griechisch',
	'hausa': 'Hausa',
	'hebrew': 'hebräisch',
	'hindi': 'Hindi',
	'hmong': 'Niederländisch',
	'hungarian': 'ungarisch',
	'iloko': 'Iloko',
	'indonesian': 'Indonesisch',
	'kannada': 'Nepalesisch',
	'khmer': 'Khmer',
	'korean': 'Koreanisch',
	'lao': 'Lao',
	'malagasy': 'Maltesisch',
	'malay': 'malaiisch',
	'malayalam': 'Lettisch',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepalesisch',
	'odia': 'Odia',
	'pashto': 'Persisch',
	'polish': 'Polieren',
	'portuguese': 'Portugiesisch',
	'punjabi': 'Punjabi',
	'russian': 'Russisch',
	'serbian': 'serbisch',
	'sindhi': 'Singhalesisch',
	'spanish': 'Spanisch',
	'swahili': 'Suaheli',
	'swedish': 'Schwedisch',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Türkisch',
	'vietnamese': 'Vietnamesisch',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Greek': {
	'title1': 'Ο Άλεφ με την Μπεθ και ο Άλφα με την Άντζελα',
	'title2': 'Προγραμματιστής μάθησης',
	'language': 'Γλώσσα',
	'Learning program': 'Πρόγραμμα εκμάθησης',
	'timePerDay': 'Χρόνος ανά ημέρα',
	'copy': 'Αντίγραφο',
	'copied': 'Αντιγράφηκε',
	'print': 'Αποτύπωμα',
	'Aleph': 'Ο Άλεφ με την Μπεθ',
	'Alpha': 'Ο Alpha με την Άντζελα',
	'afrikaans': 'Αφρικάανς',
	'albanian': 'Αλβανός',
	'amharic': 'Αμαρικά',
	'arabic': 'αραβικός',
	'assamese': 'Ασαμέζοι',
	'bengali': 'Μπενγκάλι',
	'burmese': 'Βιρμανός',
	'cebuano': 'Cebuano',
	'croatian': 'Κροατία',
	'dutch': 'Ολλανδός',
	'english': 'αγγλικός',
	'farsi': 'Φαρσί',
	'finnish': 'φινλανδικός',
	'french': 'Γάλλος',
	'fulfulde': 'Fulfulde',
	'german': 'Γερμανός',
	'greek': 'ελληνικά',
	'gujarati': 'Γκουτζαράτι',
	'hausa': 'Hausa',
	'hebrew': 'Εβραϊκά',
	'hindi': 'Χίντι',
	'hmong': 'Χμονγκ',
	'hungarian': 'ουγγρικός',
	'iloko': 'Iloko',
	'indonesian': 'Ινδονησιακά',
	'kannada': 'Κανάντα',
	'khmer': 'Χμερ',
	'korean': 'κορεάτης',
	'lao': 'Λάος',
	'malagasy': 'Μαδαγασκάρης',
	'malay': 'Μαλαισίας',
	'malayalam': 'Μαλαγιαλάμ',
	'mandarin': 'Μανταρίνι',
	'marathi': 'Μαράθι',
	'nepali': 'Νεπάλ',
	'odia': 'Odia',
	'pashto': 'Πάστο',
	'polish': 'Στίλβωση',
	'portuguese': 'Πορτογάλος',
	'punjabi': 'Παντζάμπι',
	'russian': 'ρωσικός',
	'serbian': 'Σέρβος',
	'sindhi': 'Σίντι',
	'spanish': 'ισπανικά',
	'swahili': 'Σουαχίλι',
	'swedish': 'σουηδικά',
	'tagalog': 'Ταγκαλόγκ',
	'tamil': 'Ταμίλ',
	'telugu': 'Τελούγκου',
	'thai': 'Ταϊλανδός',
	'tok pisin': 'Τοκ Πίσιν',
	'turkish': 'τούρκικος',
	'vietnamese': 'Βιετναμέζικο',
	'urdu': 'Ουρντού',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Gujarati': {
	'title1': 'બેથ સાથે અલેફ અને એન્જેલા સાથે આલ્ફા',
	'title2': 'લર્નિંગ શેડ્યૂલર',
	'language': 'ભાષા',
	'Learning program': 'શીખવાનો કાર્યક્રમ',
	'timePerDay': 'દિવસ દીઠ સમય',
	'copy': 'કૉપિ કરો',
	'copied': 'કૉપિ કર્યું',
	'print': 'પ્રિંટ',
	'Aleph': 'બેથ સાથે અલેફ',
	'Alpha': 'એન્જેલા સાથે આલ્ફા',
	'afrikaans': 'આફ્રિકન્સ',
	'albanian': 'અલ્બેનિયન',
	'amharic': 'એમ્હારિક',
	'arabic': 'અરબી',
	'assamese': 'આસામી',
	'bengali': 'બંગાળી',
	'burmese': 'બર્મીઝ',
	'cebuano': 'સિબુઆનો',
	'croatian': 'ક્રોએશિયન',
	'dutch': 'ડચ',
	'english': 'અંગ્રેજી',
	'farsi': 'ફારસી',
	'finnish': 'ફિનિશ',
	'french': 'ફ્રેન્ચ',
	'fulfulde': 'ફુલફુલડે',
	'german': 'જર્મન',
	'greek': 'ગ્રીક',
	'gujarati': 'ગુજરાતી',
	'hausa': 'હૌસા',
	'hebrew': 'હીબ્રુ',
	'hindi': 'હિન્દી',
	'hmong': 'હમોંગ',
	'hungarian': 'હંગેરિયન',
	'iloko': 'ઇલોકો',
	'indonesian': 'ઇન્ડોનેશિયન',
	'kannada': 'કન્નડ',
	'khmer': 'ખ્મેર',
	'korean': 'કોરિયન',
	'lao': 'લાઓ',
	'malagasy': 'માલાગાસી',
	'malay': 'મલય',
	'malayalam': 'મલયાલમ',
	'mandarin': 'મેન્ડરિન',
	'marathi': 'મરાઠી',
	'nepali': 'નેપાળી',
	'odia': 'ઉડિયા',
	'pashto': 'પશ્તો',
	'polish': 'પોલિશ',
	'portuguese': 'પોર્ટુગીઝ',
	'punjabi': 'પંજાબી',
	'russian': 'રશિયન',
	'serbian': 'સર્બિયન',
	'sindhi': 'સિંધી',
	'spanish': 'સ્પેનિશ',
	'swahili': 'સ્વાહિલી',
	'swedish': 'સ્વીડિશ',
	'tagalog': 'ટાગાલોગ',
	'tamil': 'તમિલ',
	'telugu': 'તેલુગુ',
	'thai': 'થાઈ',
	'tok pisin': 'ટોક પિસિન',
	'turkish': 'ટર્કિશ',
	'vietnamese': 'વિયેતનામીસ',
	'urdu': 'ઉર્દુ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Hausa': {
	'title1': 'Aleph tare da Beth da Alpha tare da Angela',
	'title2': 'Jadawalin Koyo',
	'language': 'Harshe',
	'Learning program': 'Shirin koyo',
	'timePerDay': 'Lokaci kowace rana',
	'copy': 'Kwafi',
	'copied': 'Kwafi',
	'print': 'Buga',
	'Aleph': 'Aleph tare da Beth',
	'Alpha': 'Alpha tare da Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albaniya',
	'amharic': 'Amharic',
	'arabic': 'Larabci',
	'assamese': 'Asami',
	'bengali': 'Bengali',
	'burmese': 'Burma',
	'cebuano': 'Cebuano',
	'croatian': 'Croatian',
	'dutch': 'Yaren mutanen Holland',
	'english': 'Turanci',
	'farsi': 'Farsi',
	'finnish': 'Finnish',
	'french': 'Faransanci',
	'fulfulde': 'Fulfulde',
	'german': 'Jamusanci',
	'greek': 'Girkanci',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Ibrananci',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Harshen Hungary',
	'iloko': 'Iloko',
	'indonesian': 'Indonesiya',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Yaren Koriya',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Yaren mutanen Poland',
	'portuguese': 'Fotigal',
	'punjabi': 'Punjabi',
	'russian': 'Rashanci',
	'serbian': 'Serbian',
	'sindhi': 'Sindhi',
	'spanish': 'Mutanen Espanya',
	'swahili': 'Harshen Swahili',
	'swedish': 'Yaren mutanen Sweden',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Baturke',
	'vietnamese': 'Vietnamese',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Hebrew': {
	'title1': 'אלף עם בת\' ואלפא עם אנג\'לה',
	'title2': 'מתזמן למידה',
	'language': 'שָׂפָה',
	'Learning program': 'תוכנית למידה',
	'timePerDay': 'זמן ביום',
	'copy': 'לְהַעְתִיק',
	'copied': 'מוּעֲתָק',
	'print': 'הֶדפֵּס',
	'Aleph': 'אלף עם בת\'',
	'Alpha': 'אלפא עם אנג\'לה',
	'afrikaans': 'אפריקאנס',
	'albanian': 'אלבני',
	'amharic': 'אמהרית',
	'arabic': 'עֲרָבִית',
	'assamese': 'אסאמים',
	'bengali': 'בנגלית',
	'burmese': 'בורמזי',
	'cebuano': 'סבואנו',
	'croatian': 'קרואטית',
	'dutch': 'הוֹלַנדִי',
	'english': 'אַנגְלִית',
	'farsi': 'פרסית',
	'finnish': 'פִינִית',
	'french': 'צָרְפָתִית',
	'fulfulde': 'פולפול',
	'german': 'גֶרמָנִיָת',
	'greek': 'יוונית',
	'gujarati': 'גוג\'ראטי',
	'hausa': 'האוסה',
	'hebrew': 'עִברִית',
	'hindi': 'הינדי',
	'hmong': 'המונג',
	'hungarian': 'הוּנגָרִי',
	'iloko': 'אילוקו',
	'indonesian': 'אינדונזית',
	'kannada': 'קנאדה',
	'khmer': 'חמר',
	'korean': 'קוריאנית',
	'lao': 'לאו',
	'malagasy': 'מלגזית',
	'malay': 'מלאית',
	'malayalam': 'מלאיאלאם',
	'mandarin': 'מַנדָרִין',
	'marathi': 'מראטי',
	'nepali': 'נפאלית',
	'odia': 'אודיה',
	'pashto': 'פשטו',
	'polish': 'פּוֹלָנִית',
	'portuguese': 'פורטוגזית',
	'punjabi': 'פנג\'בי',
	'russian': 'רוּסִי',
	'serbian': 'סרבית',
	'sindhi': 'סינדהי',
	'spanish': 'סְפָרַדִית',
	'swahili': 'סוואהילית',
	'swedish': 'שוודית',
	'tagalog': 'טאגלוג',
	'tamil': 'טמילית',
	'telugu': 'טלוגו',
	'thai': 'תאילנדית',
	'tok pisin': 'טוק פיסין',
	'turkish': 'טוּרקִית',
	'vietnamese': 'וייטנאמית',
	'urdu': 'אורדו',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Hindi': {
	'title1': 'एलेफ बेथ के साथ और अल्फा एंजेला के साथ',
	'title2': 'लर्निंग शेड्यूलर',
	'language': 'भाषा',
	'Learning program': 'सीखने का कार्यक्रम',
	'timePerDay': 'प्रति दिन समय',
	'copy': 'प्रतिलिपि',
	'copied': 'कॉपी किया गया',
	'print': 'छाप',
	'Aleph': 'बेथ के साथ अलेफ़',
	'Alpha': 'अल्फा और एंजेला',
	'afrikaans': 'अफ्रीकी',
	'albanian': 'अल्बानियन',
	'amharic': 'अम्हारिक्',
	'arabic': 'अरबी',
	'assamese': 'असमिया',
	'bengali': 'बंगाली',
	'burmese': 'बर्मी',
	'cebuano': 'सिबुआनो',
	'croatian': 'क्रोएशियाई',
	'dutch': 'डच',
	'english': 'अंग्रेज़ी',
	'farsi': 'फारसी',
	'finnish': 'फिनिश',
	'french': 'फ्रेंच',
	'fulfulde': 'फ़ुलफ़ुल्दे',
	'german': 'जर्मन',
	'greek': 'यूनानी',
	'gujarati': 'गुजराती',
	'hausa': 'होउसा',
	'hebrew': 'यहूदी',
	'hindi': 'हिन्दी',
	'hmong': 'हमोंग',
	'hungarian': 'हंगेरी',
	'iloko': 'इलोको',
	'indonesian': 'इन्डोनेशियाई',
	'kannada': 'कन्नडा',
	'khmer': 'खमेर',
	'korean': 'कोरियाई',
	'lao': 'लाओ',
	'malagasy': 'मालागासी',
	'malay': 'मलायी',
	'malayalam': 'मलयालम',
	'mandarin': 'अकर्मण्य',
	'marathi': 'मराठी',
	'nepali': 'नेपाली',
	'odia': 'ओडिया',
	'pashto': 'पश्तो',
	'polish': 'पोलिश',
	'portuguese': 'पुर्तगाली',
	'punjabi': 'पंजाबी',
	'russian': 'रूसी',
	'serbian': 'सर्बियाई',
	'sindhi': 'सिंधी',
	'spanish': 'स्पैनिश',
	'swahili': 'swahili',
	'swedish': 'स्वीडिश',
	'tagalog': 'तागालोग',
	'tamil': 'तामिल',
	'telugu': 'तेलुगू',
	'thai': 'थाई',
	'tok pisin': 'टोक पिसिन',
	'turkish': 'तुर्की',
	'vietnamese': 'वियतनामी',
	'urdu': 'उर्दू',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Hmong': {
	'title1': 'Aleph nrog Beth thiab Alpha nrog Angela',
	'title2': 'Kawm Scheduler',
	'language': 'Lus',
	'Learning program': 'Kev kawm',
	'timePerDay': 'Sijhawm ib hnub',
	'copy': 'Luam',
	'copied': 'Luam',
	'print': 'Luam tawm',
	'Aleph': 'Aleph nrog Beth',
	'Alpha': 'Alpha nrog Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albanian',
	'amharic': 'Amharic',
	'arabic': 'Arabic',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese',
	'cebuano': 'Cebuano',
	'croatian': 'Croatian',
	'dutch': 'Dutch',
	'english': 'Lus Askiv',
	'farsi': 'Farsi',
	'finnish': 'Finnish',
	'french': 'Fabkis',
	'fulfulde': 'Fulfulde',
	'german': 'German',
	'greek': 'Greek',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebrew',
	'hindi': 'Hindi',
	'hmong': 'Hmoob',
	'hungarian': 'Hungarian',
	'iloko': 'Iloko',
	'indonesian': 'Indonesian',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Kauslim',
	'lao': 'Nplog',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polish',
	'portuguese': 'Portuguese',
	'punjabi': 'Punjabi',
	'russian': 'Lavxias',
	'serbian': 'Serbian',
	'sindhi': 'Sindhi',
	'spanish': 'Spanish',
	'swahili': 'Swahili',
	'swedish': 'Swedish',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thaib',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turkish',
	'vietnamese': 'Nyab Laj',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Hungarian': {
	'title1': 'Aleph Beth-vel és Alfa Angelával',
	'title2': 'Tanulás ütemező',
	'language': 'Nyelv',
	'Learning program': 'Tanulási program',
	'timePerDay': 'Napi idő',
	'copy': 'Másolat',
	'copied': 'Másolva',
	'print': 'Nyomtatás',
	'Aleph': 'Aleph Beth-vel',
	'Alpha': 'Alfa Angelával',
	'afrikaans': 'afrikaans',
	'albanian': 'albán',
	'amharic': 'amhara',
	'arabic': 'arab',
	'assamese': 'asszámi',
	'bengali': 'bengáli',
	'burmese': 'burmai',
	'cebuano': 'Cebuano',
	'croatian': 'horvát',
	'dutch': 'holland',
	'english': 'angol',
	'farsi': 'perzsa',
	'finnish': 'finn',
	'french': 'francia',
	'fulfulde': 'Fullfulde',
	'german': 'német',
	'greek': 'görög',
	'gujarati': 'gudzsaráti',
	'hausa': 'Hausa',
	'hebrew': 'héber',
	'hindi': 'hindi',
	'hmong': 'hmong',
	'hungarian': 'magyar',
	'iloko': 'Iloko',
	'indonesian': 'indonéz',
	'kannada': 'kannada',
	'khmer': 'khmer',
	'korean': 'koreai',
	'lao': 'Lao',
	'malagasy': 'madagaszkári',
	'malay': 'maláj',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'marathi',
	'nepali': 'nepáli',
	'odia': 'Odia',
	'pashto': 'pastu',
	'polish': 'lengyel',
	'portuguese': 'portugál',
	'punjabi': 'pandzsábi',
	'russian': 'orosz',
	'serbian': 'szerb',
	'sindhi': 'szindhi',
	'spanish': 'spanyol',
	'swahili': 'szuahéli',
	'swedish': 'svéd',
	'tagalog': 'tagalog',
	'tamil': 'tamil',
	'telugu': 'telugu',
	'thai': 'thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'török',
	'vietnamese': 'vietnami',
	'urdu': 'urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Iloko': {
	'title1': 'Ni Aleph ken ni Beth ken ni Alpha ken ni Angela',
	'title2': 'Mangiskediul iti Panagadal',
	'language': 'Lengguahe',
	'Learning program': 'Programa ti panagsursuro',
	'timePerDay': 'Oras iti kada aldaw',
	'copy': 'Kopiaen',
	'copied': 'Nakopia',
	'print': 'Imprenta',
	'Aleph': 'Ni Aleph ken ni Beth',
	'Alpha': 'Alpha ken ni Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albaniano nga',
	'amharic': 'Amharic nga',
	'arabic': 'Arabiko nga',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese nga',
	'cebuano': 'Cebuano',
	'croatian': 'Croatiano nga',
	'dutch': 'Olandes nga Olandes',
	'english': 'Ingles',
	'farsi': 'Farsi nga',
	'finnish': 'Pinlandes',
	'french': 'Pranses nga',
	'fulfulde': 'Fulfulde',
	'german': 'Aleman nga Aleman',
	'greek': 'Griego',
	'gujarati': 'Gujarati nga',
	'hausa': 'Hausa',
	'hebrew': 'Hebreo',
	'hindi': 'Hindi nga',
	'hmong': 'Hmong',
	'hungarian': 'Hungarian nga',
	'iloko': 'Iloko',
	'indonesian': 'Indonesiano',
	'kannada': 'Kannada nga',
	'khmer': 'Khmer',
	'korean': 'Koreano',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malayo',
	'malayalam': 'Malayalam nga',
	'mandarin': 'Mandarin nga',
	'marathi': 'Marathi nga',
	'nepali': 'Nepali nga',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polish nga',
	'portuguese': 'Portuges nga pagsasao',
	'punjabi': 'Punjabi nga',
	'russian': 'Ruso nga Ruso',
	'serbian': 'Serbio nga',
	'sindhi': 'Sindhi nga',
	'spanish': 'Español',
	'swahili': 'Swahili',
	'swedish': 'Sueko nga',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai nga',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turko nga',
	'vietnamese': 'Bietnam',
	'urdu': 'Urdu nga Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Indonesian': {
	'title1': 'Aleph dengan Beth dan Alpha dengan Angela',
	'title2': 'Penjadwal Pembelajaran',
	'language': 'Bahasa',
	'Learning program': 'Program pembelajaran',
	'timePerDay': 'Waktu per hari',
	'copy': 'Menyalin',
	'copied': 'Disalin',
	'print': 'Mencetak',
	'Aleph': 'Aleph dengan Beth',
	'Alpha': 'Alfa dengan Angela',
	'afrikaans': 'Afrikanas',
	'albanian': 'bahasa Albania',
	'amharic': 'Bahasa Amharik',
	'arabic': 'Arab',
	'assamese': 'Bahasa Assam',
	'bengali': 'Benggala',
	'burmese': 'Birma',
	'cebuano': 'Bahasa Cebu',
	'croatian': 'Kroasia',
	'dutch': 'Belanda',
	'english': 'Bahasa inggris',
	'farsi': 'Bahasa Persia',
	'finnish': 'Finlandia',
	'french': 'Perancis',
	'fulfulde': 'Terpenuhi',
	'german': 'Jerman',
	'greek': 'Orang yunani',
	'gujarati': 'Bahasa Gujarati',
	'hausa': 'Bahasa Hausa',
	'hebrew': 'Ibrani',
	'hindi': 'Hindi',
	'hmong': 'Bahasa Hmong',
	'hungarian': 'Hongaria',
	'iloko': 'Iloko',
	'indonesian': 'Indonesia',
	'kannada': 'Bahasa Kannada',
	'khmer': 'Bahasa Khmer',
	'korean': 'Korea',
	'lao': 'Bahasa Laos',
	'malagasy': 'Malagasi',
	'malay': 'Melayu',
	'malayalam': 'Bahasa Malayalam',
	'mandarin': 'Bahasa Mandarin',
	'marathi': 'Bahasa Marathi',
	'nepali': 'Bahasa Nepal',
	'odia': 'Bahasa Oriya',
	'pashto': 'Bahasa Pashtun',
	'polish': 'Polandia',
	'portuguese': 'Portugis',
	'punjabi': 'Bahasa Punjab',
	'russian': 'Rusia',
	'serbian': 'Serbia',
	'sindhi': 'Bahasa Sindhi',
	'spanish': 'Spanyol',
	'swahili': 'Bahasa Swahili',
	'swedish': 'Swedia',
	'tagalog': 'Bahasa Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Bahasa Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turki',
	'vietnamese': 'Vietnam',
	'urdu': 'Bahasa Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Kannada': {
	'title1': 'ಬೆತ್ ಜೊತೆ ಅಲೆಫ್ ಮತ್ತು ಏಂಜೆಲಾ ಜೊತೆ ಆಲ್ಫಾ',
	'title2': 'ಕಲಿಕೆಯ ವೇಳಾಪಟ್ಟಿ',
	'language': 'ಭಾಷೆ',
	'Learning program': 'ಕಲಿಕಾ ಕಾರ್ಯಕ್ರಮ',
	'timePerDay': 'ದಿನಕ್ಕೆ ಸಮಯ',
	'copy': 'ನಕಲಿಸಿ',
	'copied': 'ನಕಲಿಸಲಾಗಿದೆ',
	'print': 'ಮುದ್ರಣ',
	'Aleph': 'ಬೆತ್ ಜೊತೆ ಅಲೆಫ್',
	'Alpha': 'ಏಂಜೆಲಾ ಜೊತೆ ಆಲ್ಫಾ',
	'afrikaans': 'ಆಫ್ರಿಕಾನ್ಸ್',
	'albanian': 'ಅಲ್ಬೇನಿಯನ್',
	'amharic': 'ಅಂಹರಿಕ್',
	'arabic': 'ಅರೇಬಿಕ್',
	'assamese': 'ಅಸ್ಸಾಮೀಸ್',
	'bengali': 'ಬಂಗಾಳಿ',
	'burmese': 'ಬರ್ಮೀಸ್',
	'cebuano': 'ಸೆಬುವಾನೋ',
	'croatian': 'ಕ್ರೊಯೇಷಿಯನ್',
	'dutch': 'ಡಚ್',
	'english': 'ಇಂಗ್ಲೀಷ್',
	'farsi': 'ಫಾರ್ಸಿ',
	'finnish': 'ಫಿನ್ನಿಶ್',
	'french': 'ಫ್ರೆಂಚ್',
	'fulfulde': 'ಫುಲ್ಫುಲ್ಡೆ',
	'german': 'ಜರ್ಮನ್',
	'greek': 'ಗ್ರೀಕ್',
	'gujarati': 'ಗುಜರಾತಿ',
	'hausa': 'ಹೌಸಾ',
	'hebrew': 'ಹೀಬ್ರೂ',
	'hindi': 'ಹಿಂದಿ',
	'hmong': 'ಮೋಂಗ್',
	'hungarian': 'ಹಂಗೇರಿಯನ್',
	'iloko': 'ಇಲೋಕೊ',
	'indonesian': 'ಇಂಡೋನೇಷಿಯನ್',
	'kannada': 'ಕನ್ನಡ',
	'khmer': 'ಖಮೇರ್',
	'korean': 'ಕೊರಿಯನ್',
	'lao': 'ಲಾವೋ',
	'malagasy': 'ಮಲಗಾಸಿ',
	'malay': 'ಮಲಯ',
	'malayalam': 'ಮಲಯಾಳಂ',
	'mandarin': 'ಮ್ಯಾಂಡರಿನ್',
	'marathi': 'ಮರಾಠಿ',
	'nepali': 'ನೇಪಾಳಿ',
	'odia': 'ಒಡಿಯಾ',
	'pashto': 'ಪಾಷ್ಟೋ',
	'polish': 'ಪೋಲಿಷ್',
	'portuguese': 'ಪೋರ್ಚುಗೀಸ್',
	'punjabi': 'ಪಂಜಾಬಿ',
	'russian': 'ರಷ್ಯನ್',
	'serbian': 'ಸರ್ಬಿಯನ್',
	'sindhi': 'ಸಿಂಧಿ',
	'spanish': 'ಸ್ಪ್ಯಾನಿಷ್',
	'swahili': 'ಸ್ವಾಹಿಲಿ',
	'swedish': 'ಸ್ವೀಡಿಷ್',
	'tagalog': 'ಟ್ಯಾಗಲೋಗ್',
	'tamil': 'ತಮಿಳು',
	'telugu': 'ತೆಲುಗು',
	'thai': 'ಥಾಯ್',
	'tok pisin': 'ಟೋಕ್ ಪಿಸಿನ್',
	'turkish': 'ಟರ್ಕಿಶ್',
	'vietnamese': 'ವಿಯೆಟ್ನಾಮೀಸ್',
	'urdu': 'ಉರ್ದು',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Khmer': {
	'title1': 'Aleph ជាមួយ Beth និង Alpha ជាមួយ Angela',
	'title2': 'កម្មវិធីកំណត់ពេលសិក្សា',
	'language': 'ភាសា',
	'Learning program': 'កម្មវិធីសិក្សា',
	'timePerDay': 'ពេលវេលាក្នុងមួយថ្ងៃ',
	'copy': 'ចម្លង',
	'copied': 'ចម្លង',
	'print': 'បោះពុម្ព',
	'Aleph': 'Aleph ជាមួយ Beth',
	'Alpha': 'អាល់ហ្វាជាមួយ Angela',
	'afrikaans': 'អាហ្រ្វិក',
	'albanian': 'អាល់បានី',
	'amharic': 'អាំហារិក',
	'arabic': 'ភាសាអារ៉ាប់',
	'assamese': 'អាសាំ',
	'bengali': 'បង់ក្លាដែស',
	'burmese': 'ភូមា',
	'cebuano': 'សេប៊ូណូ',
	'croatian': 'ក្រូអាត',
	'dutch': 'ហូឡង់',
	'english': 'ភាសាអង់គ្លេស',
	'farsi': 'ហ្វាស៊ី',
	'finnish': 'ហ្វាំងឡង់',
	'french': 'បារាំង',
	'fulfulde': 'ហ្វូលហ្វីល',
	'german': 'អាឡឺម៉ង់',
	'greek': 'ក្រិក',
	'gujarati': 'ហ្គូចារ៉ាទី',
	'hausa': 'ហូសា',
	'hebrew': 'ភាសាហេព្រើរ',
	'hindi': 'ហិណ្ឌូ',
	'hmong': 'ជនជាតិខ្មែរ',
	'hungarian': 'ហុងគ្រី',
	'iloko': 'អ៊ីឡូកូ',
	'indonesian': 'ឥណ្ឌូនេស៊ី',
	'kannada': 'កាណាដា',
	'khmer': 'ខ្មែរ',
	'korean': 'កូរ៉េ',
	'lao': 'ឡាវ',
	'malagasy': 'ម៉ាឡាហ្គាស៊ី',
	'malay': 'ម៉ាឡេ',
	'malayalam': 'ម៉ាឡាយ៉ាឡា',
	'mandarin': 'កុកងឺ',
	'marathi': 'ម៉ារ៉ាធី',
	'nepali': 'នេប៉ាល់',
	'odia': 'អូឌីយ៉ា',
	'pashto': 'ប៉ាសតូ',
	'polish': 'ប៉ូឡូញ',
	'portuguese': 'ព័រទុយហ្គាល់',
	'punjabi': 'ពុនចាប៊ី',
	'russian': 'រុស្សី',
	'serbian': 'ស៊ែប៊ី',
	'sindhi': 'ស៊ីនឌី',
	'spanish': 'ភាសាអេស្ប៉ាញ',
	'swahili': 'ស្វាហ៊ីលី',
	'swedish': 'ស៊ុយអែត',
	'tagalog': 'តាកាឡុក',
	'tamil': 'តាមីល',
	'telugu': 'តេលូហ្គូ',
	'thai': 'ថៃ',
	'tok pisin': 'តុក ពិសី',
	'turkish': 'ទួរគី',
	'vietnamese': 'វៀតណាម',
	'urdu': 'អ៊ូឌូ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Korean': {
	'title1': '알레프와 베스, 알파와 앤젤라',
	'title2': '학습 스케줄러',
	'language': '언어',
	'Learning program': '학습 프로그램',
	'timePerDay': '하루당 시간',
	'copy': '복사',
	'copied': '복사됨',
	'print': '인쇄',
	'Aleph': '알레프와 베스',
	'Alpha': '앤젤라와 함께하는 알파',
	'afrikaans': '아프리카 어',
	'albanian': '알바니아',
	'amharic': '암하라어',
	'arabic': '아라비아 말',
	'assamese': '아삼어',
	'bengali': '벵골 사람',
	'burmese': '버마 사람',
	'cebuano': '세부아노어',
	'croatian': '크로아티아어',
	'dutch': '네덜란드 사람',
	'english': '영어',
	'farsi': '페르시아어',
	'finnish': '핀란드어',
	'french': '프랑스 국민',
	'fulfulde': '풀풀데',
	'german': '독일 사람',
	'greek': '그리스 사람',
	'gujarati': '구자라트어',
	'hausa': '하우사어',
	'hebrew': '헤브라이 사람',
	'hindi': '힌디 어',
	'hmong': '흐몽족',
	'hungarian': '헝가리 인',
	'iloko': '일로코',
	'indonesian': '인도네시아 인',
	'kannada': '칸나다어',
	'khmer': '크메르어',
	'korean': '한국인',
	'lao': '라오어',
	'malagasy': '마다가스카르 사람',
	'malay': '말레이 사람',
	'malayalam': '말라얄람어',
	'mandarin': '만다린 오렌지',
	'marathi': '마라티어',
	'nepali': '네팔어',
	'odia': '오디아어',
	'pashto': '파슈토어',
	'polish': '광택',
	'portuguese': '포르투갈 인',
	'punjabi': '펀잡어',
	'russian': '러시아인',
	'serbian': '세르비아 사람',
	'sindhi': '신디어',
	'spanish': '스페인 사람',
	'swahili': '스와힐리어',
	'swedish': '스웨덴어',
	'tagalog': '타갈로그어',
	'tamil': '타밀 사람',
	'telugu': '텔루구어',
	'thai': '태국어',
	'tok pisin': '톡 피신',
	'turkish': '터키어',
	'vietnamese': '베트남 사람',
	'urdu': '우르두어',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Lao': {
	'title1': 'Aleph ກັບ Beth ແລະ Alpha ກັບ Angela',
	'title2': 'ຕາຕະລາງການຮຽນຮູ້',
	'language': 'ພາສາ',
	'Learning program': 'ໂຄງການການຮຽນຮູ້',
	'timePerDay': 'ເວລາຕໍ່ມື້',
	'copy': 'ສຳເນົາ',
	'copied': 'ສຳເນົາແລ້ວ',
	'print': 'ພິມ',
	'Aleph': 'Aleph ກັບ Beth',
	'Alpha': 'Alpha ກັບ Angela',
	'afrikaans': 'ອາຟຣິກາ',
	'albanian': 'ອານບານີ',
	'amharic': 'Amharic',
	'arabic': 'ອາຣັບ',
	'assamese': 'Assamese',
	'bengali': 'ເບັງກາລີ',
	'burmese': 'ມຽນມາ',
	'cebuano': 'ເຊບູອາໂນ',
	'croatian': 'ໂຄຣເອເຊຍ',
	'dutch': 'ໂຮນລັງ',
	'english': 'ພາສາອັງກິດ',
	'farsi': 'ຟາຊີ',
	'finnish': 'ຟິນແລນ',
	'french': 'ຝຣັ່ງ',
	'fulfulde': 'ຟໍຟອດ',
	'german': 'ເຢຍລະມັນ',
	'greek': 'ກຣີກ',
	'gujarati': 'ກູຈາຣາຕີ',
	'hausa': 'ໂຮຊາ',
	'hebrew': 'ເຮັບເຣີ',
	'hindi': 'ຮິນດູ',
	'hmong': 'ມົ້ງ',
	'hungarian': 'ຮັງກາຣີ',
	'iloko': 'ອິໂລໂກ',
	'indonesian': 'ອິນໂດເນເຊຍ',
	'kannada': 'ແຄນນາດາ',
	'khmer': 'ຂະເໝນ',
	'korean': 'ເກົາຫຼີ',
	'lao': 'ພາສາລາວ',
	'malagasy': 'ມາລາກາຊີ',
	'malay': 'ມາເລ',
	'malayalam': 'ມາລາຢາລາມ',
	'mandarin': 'ພາສາຈີນກາງ',
	'marathi': 'Marathi',
	'nepali': 'ເນປານ',
	'odia': 'Odia',
	'pashto': 'ພາສໂຕ',
	'polish': 'ໂປໂລຍ',
	'portuguese': 'ພາສາປອກຕຸຍການ',
	'punjabi': 'ປັນຈາບີ',
	'russian': 'ພາສາລັດເຊຍ',
	'serbian': 'ເຊີເບຍ',
	'sindhi': 'ຊິນດີ',
	'spanish': 'ແອສປາໂຍນ',
	'swahili': 'ສະວາຮິລີ',
	'swedish': 'ຊູແອັດ',
	'tagalog': 'ພາສາຕາກາລັອກ',
	'tamil': 'ທະມິນ',
	'telugu': 'ເຕລູກູ',
	'thai': 'ໄທ',
	'tok pisin': 'Tok Pisin',
	'turkish': 'ຕວກກີ',
	'vietnamese': 'ຫວຽດນາມ',
	'urdu': 'ພາສາອູດູ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Malagasy': {
	'title1': 'Aleph miaraka amin\'i Beth ary Alpha miaraka amin\'i Angela',
	'title2': 'Learning Scheduler',
	'language': 'Fiteny',
	'Learning program': 'Fandaharana fianarana',
	'timePerDay': 'Fotoana isan\'andro',
	'copy': 'dika mitovy',
	'copied': 'dika',
	'print': 'PIRINTY',
	'Aleph': 'Aleph miaraka amin\'i Beth',
	'Alpha': 'Alfa miaraka amin\'i Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'albaney',
	'amharic': 'amharic',
	'arabic': 'Arabo',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Birmana',
	'cebuano': 'Cebuano',
	'croatian': 'Kroaty',
	'dutch': 'Anarana iombonana',
	'english': 'anglisy',
	'farsi': 'Farsi',
	'finnish': 'Anarana',
	'french': 'FRANTSAY',
	'fulfulde': 'Fulfulde',
	'german': 'Anarana',
	'greek': 'GRIKA',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebreo',
	'hindi': 'hindi',
	'hmong': 'Hmong',
	'hungarian': 'hongariana',
	'iloko': 'Iloko',
	'indonesian': 'indonezianina',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Koreana',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Anarana iombonana',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'poloney',
	'portuguese': 'portogey',
	'punjabi': 'Punjabi',
	'russian': 'ROSIANINA',
	'serbian': 'serbianina',
	'sindhi': 'Sindhi',
	'spanish': 'Fikarohana',
	'swahili': 'swahili',
	'swedish': 'Anarana',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Tiorka',
	'vietnamese': 'vietnamiana',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Malay': {
	'title1': 'Aleph dengan Beth dan Alpha dengan Angela',
	'title2': 'Penjadual Pembelajaran',
	'language': 'Bahasa',
	'Learning program': 'Program pembelajaran',
	'timePerDay': 'Masa setiap hari',
	'copy': 'salin',
	'copied': 'disalin',
	'print': 'Cetak',
	'Aleph': 'Aleph dengan Beth',
	'Alpha': 'Alpha dengan Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'bahasa Albania',
	'amharic': 'Amharic',
	'arabic': 'bahasa arab',
	'assamese': 'Assam',
	'bengali': 'Benggali',
	'burmese': 'Burma',
	'cebuano': 'Cebuano',
	'croatian': 'bahasa Croatia',
	'dutch': 'Belanda',
	'english': 'Inggeris',
	'farsi': 'Farsi',
	'finnish': 'bahasa Finland',
	'french': 'Perancis',
	'fulfulde': 'Fulfulde',
	'german': 'Jerman',
	'greek': 'bahasa Yunani',
	'gujarati': 'Gujerat',
	'hausa': 'Hausa',
	'hebrew': 'bahasa Ibrani',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'bahasa Hungary',
	'iloko': 'Iloko',
	'indonesian': 'Indonesia',
	'kannada': 'Kannada',
	'khmer': 'bahasa Khmer',
	'korean': 'Korea',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Melayu',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepal',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Poland',
	'portuguese': 'Portugis',
	'punjabi': 'Punjabi',
	'russian': 'bahasa Rusia',
	'serbian': 'bahasa Serbia',
	'sindhi': 'Sindhi',
	'spanish': 'bahasa Sepanyol',
	'swahili': 'bahasa Swahili',
	'swedish': 'bahasa Sweden',
	'tagalog': 'bahasa Tagalog',
	'tamil': 'bahasa Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'bahasa Turki',
	'vietnamese': 'bahasa Vietnam',
	'urdu': 'bahasa Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Malayalam': {
	'title1': 'ബെത്തിനൊപ്പം ആലെഫും ആഞ്ചലയ്‌ക്കൊപ്പം ആൽഫയും',
	'title2': 'ലേണിംഗ് ഷെഡ്യൂളർ',
	'language': 'ഭാഷ',
	'Learning program': 'പഠന പരിപാടി',
	'timePerDay': 'ദിവസത്തിലെ സമയം',
	'copy': 'പകർത്തുക',
	'copied': 'പകർത്തി',
	'print': 'അച്ചടിക്കുക',
	'Aleph': 'ബെത്തിനൊപ്പം ആലെഫ്',
	'Alpha': 'ആഞ്ചലയ്‌ക്കൊപ്പം ആൽഫ',
	'afrikaans': 'ആഫ്രിക്കാൻസ്',
	'albanian': 'അൽബേനിയൻ',
	'amharic': 'അംഹാരിക്',
	'arabic': 'അറബിക്',
	'assamese': 'ആസാമീസ്',
	'bengali': 'ബംഗാളി',
	'burmese': 'ബർമീസ്',
	'cebuano': 'സെബുവാനോ',
	'croatian': 'ക്രൊയേഷ്യൻ',
	'dutch': 'ഡച്ച്',
	'english': 'ഇംഗ്ലീഷ്',
	'farsi': 'ഫാർസി',
	'finnish': 'ഫിന്നിഷ്',
	'french': 'ഫ്രഞ്ച്',
	'fulfulde': 'ഫുൾഫുൾഡെ',
	'german': 'ജർമ്മൻ',
	'greek': 'ഗ്രീക്ക്',
	'gujarati': 'ഗുജറാത്തി',
	'hausa': 'ഹൗസ',
	'hebrew': 'ഹീബ്രു',
	'hindi': 'ഹിന്ദി',
	'hmong': 'ഹ്മോങ്',
	'hungarian': 'ഹംഗേറിയൻ',
	'iloko': 'ഇലോക്കോ',
	'indonesian': 'ഇന്തോനേഷ്യൻ',
	'kannada': 'കന്നഡ',
	'khmer': 'ഖെമർ',
	'korean': 'കൊറിയൻ',
	'lao': 'ലാവോ',
	'malagasy': 'മലഗാസി',
	'malay': 'മലായ്',
	'malayalam': 'മലയാളം',
	'mandarin': 'മന്ദാരിൻ',
	'marathi': 'മറാത്തി',
	'nepali': 'നേപ്പാളി',
	'odia': 'ഒഡിയ',
	'pashto': 'പഷ്തോ',
	'polish': 'പോളിഷ്',
	'portuguese': 'പോർച്ചുഗീസ്',
	'punjabi': 'പഞ്ചാബി',
	'russian': 'റഷ്യൻ',
	'serbian': 'സെർബിയൻ',
	'sindhi': 'സിന്ധി',
	'spanish': 'സ്പാനിഷ്',
	'swahili': 'സ്വാഹിലി',
	'swedish': 'സ്വീഡിഷ്',
	'tagalog': 'ടാഗലോഗ്',
	'tamil': 'തമിഴ്',
	'telugu': 'തെലുങ്ക്',
	'thai': 'തായ്',
	'tok pisin': 'ടോക് പിസിൻ',
	'turkish': 'ടർക്കിഷ്',
	'vietnamese': 'വിയറ്റ്നാമീസ്',
	'urdu': 'ഉറുദു',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Mandarin': {
	'title1': 'Aleph 与 Beth 以及 Alpha 与 Angela',
	'title2': '学习计划',
	'language': '语言',
	'Learning program': '学习计划',
	'timePerDay': '每天时间',
	'copy': '复制',
	'copied': '已复制',
	'print': '打印',
	'Aleph': 'Aleph 和 Beth 在一起',
	'Alpha': 'Alpha 与 Angela',
	'afrikaans': '南非荷兰语',
	'albanian': '阿尔巴尼亚语',
	'amharic': '阿姆哈拉语',
	'arabic': '阿拉伯',
	'assamese': '阿萨姆语',
	'bengali': '孟加拉',
	'burmese': '缅甸语',
	'cebuano': '宿务语',
	'croatian': '克罗地亚语',
	'dutch': '荷兰语',
	'english': '英语',
	'farsi': '波斯语',
	'finnish': '芬兰',
	'french': '法语',
	'fulfulde': '富尔富德',
	'german': '德语',
	'greek': '希腊语',
	'gujarati': '古吉拉特语',
	'hausa': '豪萨语',
	'hebrew': '希伯来语',
	'hindi': '印地语',
	'hmong': '苗族',
	'hungarian': '匈牙利',
	'iloko': '伊洛科',
	'indonesian': '印度尼西亚',
	'kannada': '卡纳达语',
	'khmer': '高棉语',
	'korean': '韩国人',
	'lao': '老挝',
	'malagasy': '马尔加什',
	'malay': '马来语',
	'malayalam': '马拉雅拉姆语',
	'mandarin': '普通话',
	'marathi': '马拉地语',
	'nepali': '尼泊尔语',
	'odia': '奥迪亚语',
	'pashto': '普什图语',
	'polish': '抛光',
	'portuguese': '葡萄牙语',
	'punjabi': '旁遮普语',
	'russian': '俄语',
	'serbian': '塞尔维亚',
	'sindhi': '信德语',
	'spanish': '西班牙语',
	'swahili': '斯瓦希里语',
	'swedish': '瑞典',
	'tagalog': '他加禄语',
	'tamil': '泰米尔语',
	'telugu': '泰卢固语',
	'thai': '泰国',
	'tok pisin': '托克皮辛语',
	'turkish': '土耳其',
	'vietnamese': '越南语',
	'urdu': '乌尔都语',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Marathi': {
	'title1': 'बेथसोबत अलेफ आणि अँजेलासोबत अल्फा',
	'title2': 'लर्निंग शेड्यूलर',
	'language': 'भाषा',
	'Learning program': 'शिकण्याचा कार्यक्रम',
	'timePerDay': 'दररोज वेळ',
	'copy': 'कॉपी करा',
	'copied': 'कॉपी केले',
	'print': 'प्रिंट',
	'Aleph': 'बेथसोबत अलेफ',
	'Alpha': 'अँजेलासोबत अल्फा',
	'afrikaans': 'आफ्रिकान्स',
	'albanian': 'अल्बेनियन',
	'amharic': 'अम्हारिक',
	'arabic': 'अरबी',
	'assamese': 'आसामी',
	'bengali': 'बंगाली',
	'burmese': 'बर्मीज',
	'cebuano': 'सेबुआनो',
	'croatian': 'क्रोएशियन',
	'dutch': 'डच',
	'english': 'इंग्रजी',
	'farsi': 'फारसी',
	'finnish': 'फिनिश',
	'french': 'फ्रेंच',
	'fulfulde': 'फुलफुलदे',
	'german': 'जर्मन',
	'greek': 'ग्रीक',
	'gujarati': 'गुजराती',
	'hausa': 'हौसा',
	'hebrew': 'हिब्रू',
	'hindi': 'हिंदी',
	'hmong': 'ह्मोंग',
	'hungarian': 'हंगेरियन',
	'iloko': 'इलोको',
	'indonesian': 'इंडोनेशियन',
	'kannada': 'कन्नड',
	'khmer': 'ख्मेर',
	'korean': 'कोरियन',
	'lao': 'लाओ',
	'malagasy': 'मालागासी',
	'malay': 'मलय',
	'malayalam': 'मल्याळम',
	'mandarin': 'मंदारिन',
	'marathi': 'मराठी',
	'nepali': 'नेपाळी',
	'odia': 'ओडिया',
	'pashto': 'पश्तो',
	'polish': 'पोलिश',
	'portuguese': 'पोर्तुगीज',
	'punjabi': 'पंजाबी',
	'russian': 'रशियन',
	'serbian': 'सर्बियन',
	'sindhi': 'सिंधी',
	'spanish': 'स्पॅनिश',
	'swahili': 'स्वाहिली',
	'swedish': 'स्वीडिश',
	'tagalog': 'टागालोग',
	'tamil': 'तमिळ',
	'telugu': 'तेलगू',
	'thai': 'थाई',
	'tok pisin': 'टोक पिसिन',
	'turkish': 'तुर्की',
	'vietnamese': 'व्हिएतनामी',
	'urdu': 'उर्दू',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Nepali': {
	'title1': 'बेथसँग एलेफ र एन्जेलासँग अल्फा',
	'title2': 'सिकाइ तालिकाकर्ता',
	'language': 'भाषा',
	'Learning program': 'सिकाइ कार्यक्रम',
	'timePerDay': 'प्रति दिन समय',
	'copy': 'प्रतिलिपि गर्नुहोस्',
	'copied': 'प्रतिलिपि गरियो',
	'print': 'छापा',
	'Aleph': 'बेथसँग एलेफ',
	'Alpha': 'एन्जेलासँग अल्फा',
	'afrikaans': 'अफ्रिकीहरू',
	'albanian': 'अल्बेनियाली',
	'amharic': 'अम्हारिक',
	'arabic': 'अरबी',
	'assamese': 'आसामी',
	'bengali': 'बंगाली',
	'burmese': 'बर्मेली',
	'cebuano': 'सेबुआनो',
	'croatian': 'क्रोएसियाली',
	'dutch': 'डच',
	'english': 'अंग्रेजी',
	'farsi': 'फारसी',
	'finnish': 'फिनिस',
	'french': 'फ्रान्सेली',
	'fulfulde': 'फुलफुल्डे',
	'german': 'जर्मन',
	'greek': 'ग्रीक',
	'gujarati': 'गुजराती',
	'hausa': 'हौसा',
	'hebrew': 'हिब्रू',
	'hindi': 'हिन्दी',
	'hmong': 'हमोङ',
	'hungarian': 'हंगेरी',
	'iloko': 'इलोको',
	'indonesian': 'इन्डोनेसियाली',
	'kannada': 'कन्नड',
	'khmer': 'खमेर',
	'korean': 'कोरियाली',
	'lao': 'लाओ',
	'malagasy': 'मालागासी',
	'malay': 'मलेसियाली',
	'malayalam': 'मलयालम',
	'mandarin': 'मन्डारिन',
	'marathi': 'मराठी',
	'nepali': 'नेपाली',
	'odia': 'उडिया',
	'pashto': 'पश्तो',
	'polish': 'पोलिश',
	'portuguese': 'पोर्चुगिज',
	'punjabi': 'पञ्जाबी',
	'russian': 'रुसी',
	'serbian': 'सर्बियाली',
	'sindhi': 'सिन्धी',
	'spanish': 'स्पेनी',
	'swahili': 'स्वाहिली',
	'swedish': 'स्विडेनी',
	'tagalog': 'तागालोग',
	'tamil': 'तमिल',
	'telugu': 'तेलुगु',
	'thai': 'थाई',
	'tok pisin': 'टोक पिसिन',
	'turkish': 'टर्की',
	'vietnamese': 'भियतनामी',
	'urdu': 'उर्दू',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Odia': {
	'title1': 'ବେଥ୍ ସହିତ ଆଲେଫ୍ ଏବଂ ଆଞ୍ଜେଲା ସହିତ ଆଲଫା',
	'title2': 'ଶିକ୍ଷଣ ସୂଚକ',
	'language': 'ଭାଷା',
	'Learning program': 'ଶିକ୍ଷଣ କାର୍ଯ୍ୟକ୍ରମ',
	'timePerDay': 'ଦିନ ପିଛା ସମୟ',
	'copy': 'କପି କରନ୍ତୁ',
	'copied': 'କପି କରାଯାଇଛି',
	'print': 'ପ୍ରିଣ୍ଟ କରନ୍ତୁ',
	'Aleph': 'ବେଥ୍ ସହିତ ଆଲେଫ୍',
	'Alpha': 'ଆଞ୍ଜେଲାଙ୍କ ସହିତ ଆଲଫା',
	'afrikaans': 'ଆଫ୍ରିକୀୟ',
	'albanian': 'ଆଲବାନିଆନ୍',
	'amharic': 'ଆମହାରିକ୍',
	'arabic': 'ଆରବିକ',
	'assamese': 'ଆସାମୀୟ',
	'bengali': 'ବଙ୍ଗାଳୀ',
	'burmese': 'ବର୍ମିଜ୍',
	'cebuano': 'ସେବୁଆନୋ',
	'croatian': 'କ୍ରୋଏସୀୟ',
	'dutch': 'ଡଚ୍',
	'english': 'ଇଂରାଜୀ',
	'farsi': 'ଫାର୍ସୀ',
	'finnish': 'ଫିନିସ୍',
	'french': 'ଫରାସୀ',
	'fulfulde': 'ଫୁଲଫୁଲଡେ',
	'german': 'ଜର୍ମାନ',
	'greek': 'ଗ୍ରୀକ୍',
	'gujarati': 'ଗୁଜୁରାଟୀ',
	'hausa': 'ହାଉସା',
	'hebrew': 'ହିବ୍ରୁ',
	'hindi': 'ହିନ୍ଦୀ',
	'hmong': 'ମୋଙ୍ଗ',
	'hungarian': 'ହଙ୍ଗେରୀୟ',
	'iloko': 'ଇଲୋକୋ',
	'indonesian': 'ଇଣ୍ଡୋନେସୀୟ',
	'kannada': 'କନ୍ନଡ',
	'khmer': 'ଖମେର୍',
	'korean': 'କୋରୀୟ',
	'lao': 'ଲାଓ',
	'malagasy': 'ମାଲାଗାସୀ',
	'malay': 'ମାଲାୟ',
	'malayalam': 'ମାଲାୟଲମ',
	'mandarin': 'ମାଣ୍ଡାରିନ୍‌',
	'marathi': 'ମରାଠୀ',
	'nepali': 'ନେପାଳୀ',
	'odia': 'ଓଡ଼ିଆ',
	'pashto': 'ପାସ୍ତୋ',
	'polish': 'ପୋଲିସ୍',
	'portuguese': 'ପର୍ତ୍ତୁଗୀଜ୍',
	'punjabi': 'ପଞ୍ଜାବୀ',
	'russian': 'ଋଷୀୟ',
	'serbian': 'ସର୍ବିଆନ୍',
	'sindhi': 'ସିନ୍ଧି',
	'spanish': 'ସ୍ପାନିସ୍',
	'swahili': 'ସ୍ୱାହିଲି',
	'swedish': 'ସ୍ୱିଡିସ୍',
	'tagalog': 'ଟ୍ୟାଗଲଗ୍',
	'tamil': 'ତାମିଲ୍',
	'telugu': 'ତେଲୁଗୁ',
	'thai': 'ଥାଇ',
	'tok pisin': 'ଟୋକ୍ ପିସିନ୍',
	'turkish': 'ତୁର୍କିସ୍',
	'vietnamese': 'ଭିଏତନାମିୟ',
	'urdu': 'ଉର୍ଦ୍ଦୁ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Pashto': {
	'title1': 'الف د بیت سره او الفا د انجیلا سره',
	'title2': 'د زده کړې مهالویش کوونکی',
	'language': 'ژبه',
	'Learning program': 'د زده کړې پروګرام',
	'timePerDay': 'په ورځ کې وخت',
	'copy': 'کاپي',
	'copied': 'کاپي شوی',
	'print': 'چاپ',
	'Aleph': 'الف د بیت سره',
	'Alpha': 'الفا د انجیلا سره',
	'afrikaans': 'افریقایی',
	'albanian': 'البانیایی',
	'amharic': 'امهاریک',
	'arabic': 'عربي',
	'assamese': 'آسامي',
	'bengali': 'بنګالي',
	'burmese': 'برمایی',
	'cebuano': 'سیبوانو',
	'croatian': 'کرواسین',
	'dutch': 'الماني',
	'english': 'انګلیسي',
	'farsi': 'فارسي',
	'finnish': 'فنلینډي',
	'french': 'فرانسوي',
	'fulfulde': 'فولفولډ',
	'german': 'جرمني',
	'greek': 'یوناني',
	'gujarati': 'ګجراتي',
	'hausa': 'هوسا',
	'hebrew': 'عبري',
	'hindi': 'هندي',
	'hmong': 'همونګ',
	'hungarian': 'هنګري',
	'iloko': 'ایلوکو',
	'indonesian': 'انډونیزین',
	'kannada': 'کناډا',
	'khmer': 'خمیر',
	'korean': 'کوریایی',
	'lao': 'لاو',
	'malagasy': 'ملاګاسي',
	'malay': 'مالایا',
	'malayalam': 'ملایلم',
	'mandarin': 'مانډرین',
	'marathi': 'مراټي',
	'nepali': 'نیپالي',
	'odia': 'اوډیا',
	'pashto': 'پښتو',
	'polish': 'پولیش',
	'portuguese': 'پورتګالي',
	'punjabi': 'پنجابي',
	'russian': 'روسي',
	'serbian': 'صربي',
	'sindhi': 'سندي',
	'spanish': 'هسپانیه ایی',
	'swahili': 'سواحلي',
	'swedish': 'سویډیش یا سویډني',
	'tagalog': 'تګالوګ',
	'tamil': 'تامیل',
	'telugu': 'تولیګو',
	'thai': 'تای',
	'tok pisin': 'ټوک پيسين',
	'turkish': 'ترکي',
	'vietnamese': 'ویتنامي',
	'urdu': 'اردو',
	'direction': 'RTL',
	'font': 'Arial',
	},
'Polish': {
	'title1': 'Aleph z Beth i Alpha z Angelą',
	'title2': 'Harmonogram nauki',
	'language': 'Język',
	'Learning program': 'Program nauczania',
	'timePerDay': 'Czas na dzień',
	'copy': 'Kopia',
	'copied': 'Skopiowano',
	'print': 'Wydrukować',
	'Aleph': 'Aleph z Beth',
	'Alpha': 'Alfa z Angelą',
	'afrikaans': 'Afrykanerski',
	'albanian': 'albański',
	'amharic': 'amharski',
	'arabic': 'arabski',
	'assamese': 'Asamski',
	'bengali': 'bengalski',
	'burmese': 'Birmańczyk',
	'cebuano': 'Cebuański',
	'croatian': 'chorwacki',
	'dutch': 'Holenderski',
	'english': 'angielski',
	'farsi': 'perski',
	'finnish': 'fiński',
	'french': 'francuski',
	'fulfulde': 'Wypełniać',
	'german': 'niemiecki',
	'greek': 'grecki',
	'gujarati': 'Gudżarati',
	'hausa': 'hausański',
	'hebrew': 'hebrajski',
	'hindi': 'hinduski',
	'hmong': 'Hmong',
	'hungarian': 'węgierski',
	'iloko': 'Ilok',
	'indonesian': 'indonezyjski',
	'kannada': 'kannadajski',
	'khmer': 'khmerski',
	'korean': 'koreański',
	'lao': 'Laotański',
	'malagasy': 'malgaski',
	'malay': 'malajski',
	'malayalam': 'Malajalam',
	'mandarin': 'Mandarynka',
	'marathi': 'Marathi',
	'nepali': 'Nepalski',
	'odia': 'Odija',
	'pashto': 'paszto',
	'polish': 'Polski',
	'portuguese': 'portugalski',
	'punjabi': 'Pendżabski',
	'russian': 'rosyjski',
	'serbian': 'serbski',
	'sindhi': 'Sindhi',
	'spanish': 'hiszpański',
	'swahili': 'suahilijski',
	'swedish': 'szwedzki',
	'tagalog': 'tagalski',
	'tamil': 'Tamil',
	'telugu': 'teluguski',
	'thai': 'tajski',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turecki',
	'vietnamese': 'wietnamski',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Portuguese': {
	'title1': 'Aleph com Beth e Alpha com Angela',
	'title2': 'Agendador de Aprendizagem',
	'language': 'Linguagem',
	'Learning program': 'Programa de aprendizagem',
	'timePerDay': 'Tempo por dia',
	'copy': 'Cópia',
	'copied': 'Copiado',
	'print': 'Imprimir',
	'Aleph': 'Aleph com Beth',
	'Alpha': 'Alfa com Angela',
	'afrikaans': 'afrikaans',
	'albanian': 'albanês',
	'amharic': 'Amárico',
	'arabic': 'árabe',
	'assamese': 'Assameses',
	'bengali': 'bengali',
	'burmese': 'birmanês',
	'cebuano': 'Cebuano',
	'croatian': 'croata',
	'dutch': 'Holandês',
	'english': 'Inglês',
	'farsi': 'Farsi',
	'finnish': 'finlandês',
	'french': 'Francês',
	'fulfulde': 'Completo',
	'german': 'Alemão',
	'greek': 'grego',
	'gujarati': 'Português',
	'hausa': 'Hauçá',
	'hebrew': 'hebraico',
	'hindi': 'hindi',
	'hmong': 'Hmong',
	'hungarian': 'húngaro',
	'iloko': 'Iloco',
	'indonesian': 'indonésio',
	'kannada': 'Canarês',
	'khmer': 'Khmer',
	'korean': 'coreano',
	'lao': 'Laosiano',
	'malagasy': 'malgaxe',
	'malay': 'malaio',
	'malayalam': 'Malaiala',
	'mandarin': 'Mandarim',
	'marathi': 'Marathi',
	'nepali': 'Nepalês',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'polonês',
	'portuguese': 'Português',
	'punjabi': 'Português',
	'russian': 'russo',
	'serbian': 'sérvio',
	'sindhi': 'Sindi',
	'spanish': 'Espanhol',
	'swahili': 'Suaíli',
	'swedish': 'sueco',
	'tagalog': 'Tagalo',
	'tamil': 'tâmil',
	'telugu': 'Télugo',
	'thai': 'tailandês',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turco',
	'vietnamese': 'vietnamita',
	'urdu': 'urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Punjabi': {
	'title1': 'ਅਲੇਫ਼ ਬੈਥ ਨਾਲ ਅਤੇ ਅਲਫ਼ਾ ਐਂਜੇਲਾ ਨਾਲ',
	'title2': 'ਲਰਨਿੰਗ ਸ਼ਡਿਊਲਰ',
	'language': 'ਭਾਸ਼ਾ',
	'Learning program': 'ਸਿਖਲਾਈ ਪ੍ਰੋਗਰਾਮ',
	'timePerDay': 'ਪ੍ਰਤੀ ਦਿਨ ਸਮਾਂ',
	'copy': 'ਕਾਪੀ ਕਰੋ',
	'copied': 'ਕਾਪੀ ਕੀਤਾ ਗਿਆ',
	'print': 'ਪ੍ਰਿੰਟ',
	'Aleph': 'ਬੈਥ ਦੇ ਨਾਲ ਅਲੇਫ਼',
	'Alpha': 'ਐਂਜੇਲਾ ਦੇ ਨਾਲ ਅਲਫ਼ਾ',
	'afrikaans': 'ਅਫ਼ਰੀਕੀ',
	'albanian': 'ਅਲਬਾਨੀਅਨ',
	'amharic': 'ਅਮਹਾਰਿਕ',
	'arabic': 'ਅਰਬੀ',
	'assamese': 'ਅਸਾਮੀ',
	'bengali': 'ਬੰਗਾਲੀ',
	'burmese': 'ਬਰਮੀ',
	'cebuano': 'ਸੇਬੂਆਨੋ',
	'croatian': 'ਕ੍ਰੋਏਸ਼ੀਆਈ',
	'dutch': 'ਡੱਚ',
	'english': 'ਅੰਗਰੇਜ਼ੀ',
	'farsi': 'ਫਾਰਸੀ',
	'finnish': 'ਫਿਨਿਸ਼',
	'french': 'ਫ੍ਰੈਂਚ',
	'fulfulde': 'ਫੁਲਫੁਲਡੇ',
	'german': 'ਜਰਮਨ',
	'greek': 'ਯੂਨਾਨੀ',
	'gujarati': 'ਗੁਜਰਾਤੀ',
	'hausa': 'ਹਾਉਸਾ',
	'hebrew': 'ਇਬਰਾਨੀ',
	'hindi': 'ਹਿੰਦੀ',
	'hmong': 'ਹਮੋਂਗ',
	'hungarian': 'ਹੰਗਰੀਆਈ',
	'iloko': 'ਇਲੋਕੋ',
	'indonesian': 'ਇੰਡੋਨੇਸ਼ੀਆਈ',
	'kannada': 'ਕੰਨੜ',
	'khmer': 'ਖਮੇਰ',
	'korean': 'ਕੋਰੀਆਈ',
	'lao': 'ਲਾਓ',
	'malagasy': 'ਮਾਲਾਗਾਸੀ',
	'malay': 'ਮਾਲੇਈ',
	'malayalam': 'ਮਲਿਆਲਮ',
	'mandarin': 'ਮੈਂਡਰਿਨ',
	'marathi': 'ਮਰਾਠੀ',
	'nepali': 'ਨੇਪਾਲੀ',
	'odia': 'ਉੜੀਆ',
	'pashto': 'ਪਸ਼ਤੋ',
	'polish': 'ਪੋਲਿਸ਼',
	'portuguese': 'ਪੁਰਤਗਾਲੀ',
	'punjabi': 'ਪੰਜਾਬੀ',
	'russian': 'ਰੂਸੀ',
	'serbian': 'ਸਰਬੀਆਈ',
	'sindhi': 'ਸਿੰਧੀ',
	'spanish': 'ਸਪੈਨਿਸ਼',
	'swahili': 'ਸਵਾਹਿਲੀ',
	'swedish': 'ਸਵੀਡਿਸ਼',
	'tagalog': 'ਤਾਗਾਲੋਗ',
	'tamil': 'ਤਾਮਿਲ',
	'telugu': 'ਤੇਲਗੂ',
	'thai': 'ਥਾਈ',
	'tok pisin': 'ਟੋਕ ਪਿਸਿਨ',
	'turkish': 'ਤੁਰਕੀ',
	'vietnamese': 'ਵੀਅਤਨਾਮੀ',
	'urdu': 'ਉਰਦੂ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Russian': {
	'title1': 'Алеф с Бет и Альфа с Анджелой',
	'title2': 'Планировщик обучения',
	'language': 'Язык',
	'Learning program': 'Программа обучения',
	'timePerDay': 'Время в день',
	'copy': 'Копировать',
	'copied': 'Скопировано',
	'print': 'Печать',
	'Aleph': 'Алеф с Бет',
	'Alpha': 'Альфа с Анджелой',
	'afrikaans': 'африкаанс',
	'albanian': 'албанский',
	'amharic': 'амхарский',
	'arabic': 'арабский',
	'assamese': 'ассамский',
	'bengali': 'бенгальский',
	'burmese': 'бирманский',
	'cebuano': 'себуанский',
	'croatian': 'хорватский',
	'dutch': 'Голландский',
	'english': 'Английский',
	'farsi': 'фарси',
	'finnish': 'финский',
	'french': 'Французский',
	'fulfulde': 'Фулфулде',
	'german': 'немецкий',
	'greek': 'греческий',
	'gujarati': 'гуджарати',
	'hausa': 'хауса',
	'hebrew': 'иврит',
	'hindi': 'хинди',
	'hmong': 'Хмонг',
	'hungarian': 'венгерский',
	'iloko': 'Илоко',
	'indonesian': 'индонезийский',
	'kannada': 'каннада',
	'khmer': 'кхмерский',
	'korean': 'корейский',
	'lao': 'Лаосский',
	'malagasy': 'малагасийский',
	'malay': 'малайский',
	'malayalam': 'малаялам',
	'mandarin': 'Мандарин',
	'marathi': 'маратхи',
	'nepali': 'непальский',
	'odia': 'Одиа',
	'pashto': 'пушту',
	'polish': 'польский',
	'portuguese': 'португальский',
	'punjabi': 'пенджаби',
	'russian': 'Русский',
	'serbian': 'сербский',
	'sindhi': 'Синдхи',
	'spanish': 'испанский',
	'swahili': 'суахили',
	'swedish': 'шведский',
	'tagalog': 'тагальский',
	'tamil': 'тамильский',
	'telugu': 'телугу',
	'thai': 'тайский',
	'tok pisin': 'Ток Писин',
	'turkish': 'турецкий',
	'vietnamese': 'вьетнамский',
	'urdu': 'урду',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Serbian': {
	'title1': 'Алеф са Бет и Алфа са Анђелом',
	'title2': 'Планер учења',
	'language': 'Језик',
	'Learning program': 'Програм учења',
	'timePerDay': 'Време по дану',
	'copy': 'Копирај',
	'copied': 'Копирано',
	'print': 'Принт',
	'Aleph': 'Алеф са Бет',
	'Alpha': 'Алфа са Анђелом',
	'afrikaans': 'Африкаанс',
	'albanian': 'Албанац',
	'amharic': 'амхарски',
	'arabic': 'арапски',
	'assamese': 'Асамски',
	'bengali': 'бенгалски',
	'burmese': 'бурмански',
	'cebuano': 'Цебуано',
	'croatian': 'хрватски',
	'dutch': 'холандски',
	'english': 'енглески',
	'farsi': 'фарси',
	'finnish': 'фински',
	'french': 'француски',
	'fulfulde': 'Фулфулде',
	'german': 'немачки',
	'greek': 'грчки',
	'gujarati': 'гуџарати',
	'hausa': 'Хауса',
	'hebrew': 'хебрејски',
	'hindi': 'Хинди',
	'hmong': 'Хмонг',
	'hungarian': 'мађарски',
	'iloko': 'Илоко',
	'indonesian': 'индонезијски',
	'kannada': 'канада',
	'khmer': 'кмерски',
	'korean': 'Кореан',
	'lao': 'Лао',
	'malagasy': 'малгашки',
	'malay': 'малајски',
	'malayalam': 'малајалам',
	'mandarin': 'Мандарин',
	'marathi': 'Маратхи',
	'nepali': 'непалски',
	'odia': 'Одиа',
	'pashto': 'пашто',
	'polish': 'пољски',
	'portuguese': 'португалски',
	'punjabi': 'панџапски',
	'russian': 'руски',
	'serbian': 'српски',
	'sindhi': 'Синдхи',
	'spanish': 'шпански',
	'swahili': 'свахили',
	'swedish': 'шведски',
	'tagalog': 'Тагалог',
	'tamil': 'тамилски',
	'telugu': 'телугу',
	'thai': 'тајландски',
	'tok pisin': 'Ток Писин',
	'turkish': 'турски',
	'vietnamese': 'вијетнамски',
	'urdu': 'Урду',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Sindhi': {
	'title1': 'الف بيٿ سان ۽ الفا اينجلا سان',
	'title2': 'سکيا جو شيڊولر',
	'language': 'ٻولي',
	'Learning program': 'سکيا جو پروگرام',
	'timePerDay': 'ڏينهن جو وقت',
	'copy': 'ڪاپي',
	'copied': 'ڪاپي ٿيل',
	'print': 'پرنٽ',
	'Aleph': 'الف بيٿ سان گڏ',
	'Alpha': 'اينجلا سان الفا',
	'afrikaans': 'آفريڪي',
	'albanian': 'الباني',
	'amharic': 'امهاري',
	'arabic': 'عربي',
	'assamese': 'آسامي',
	'bengali': 'بنگالي',
	'burmese': 'برمي',
	'cebuano': 'سيبوانو',
	'croatian': 'ڪروشيائي',
	'dutch': 'ڊچ ٻولي',
	'english': 'انگريزي',
	'farsi': 'فارسي',
	'finnish': 'فني',
	'french': 'فرانسي',
	'fulfulde': 'فلفلڊ',
	'german': 'جرمني',
	'greek': 'يوناني',
	'gujarati': 'گجراتي',
	'hausa': 'هوسا ٻولي',
	'hebrew': 'عبراني',
	'hindi': 'هندي',
	'hmong': 'همنگي',
	'hungarian': 'هنگري',
	'iloko': 'ايلوڪو',
	'indonesian': 'انڊونيشي',
	'kannada': 'ڪنادي',
	'khmer': 'خمير',
	'korean': 'ڪورين',
	'lao': 'لائو',
	'malagasy': 'ملاگاسي',
	'malay': 'مالائي',
	'malayalam': 'مالايالم',
	'mandarin': 'مينڊرين',
	'marathi': 'مراٺي',
	'nepali': 'نيپالي',
	'odia': 'اوڊيا',
	'pashto': 'پشتو',
	'polish': 'پالش',
	'portuguese': 'پرتگالي',
	'punjabi': 'پنجابي',
	'russian': 'روسي',
	'serbian': 'سربيائي',
	'sindhi': 'سنڌي',
	'spanish': 'اندلسي',
	'swahili': 'سواهلي',
	'swedish': 'سويڊني',
	'tagalog': 'تگلگ ٻولي',
	'tamil': 'تاملي',
	'telugu': 'تيلوگو ٻولي',
	'thai': 'ٿائي ٻولي',
	'tok pisin': 'ٽوڪ پسين',
	'turkish': 'ترڪي',
	'vietnamese': 'ويٽنامي',
	'urdu': 'اردو',
	'direction': 'RTL',
	'font': 'Lateef',
	},
'Spanish': {
	'title1': 'Aleph con Beth y Alpha con Angela',
	'title2': 'Programador de aprendizaje',
	'language': 'Idioma',
	'Learning program': 'Programa de aprendizaje',
	'timePerDay': 'Tiempo por día',
	'copy': 'Copiar',
	'copied': 'Copiado',
	'print': 'Imprimir',
	'Aleph': 'Aleph con Beth',
	'Alpha': 'Alfa con Angela',
	'afrikaans': 'africaans',
	'albanian': 'albanés',
	'amharic': 'Amárico',
	'arabic': 'árabe',
	'assamese': 'Assamese',
	'bengali': 'bengalí',
	'burmese': 'birmano',
	'cebuano': 'Cebuano',
	'croatian': 'croata',
	'dutch': 'Holandés',
	'english': 'Inglés',
	'farsi': 'persa',
	'finnish': 'finlandés',
	'french': 'Francés',
	'fulfulde': 'Fulfulde',
	'german': 'Alemán',
	'greek': 'Griego',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'hebreo',
	'hindi': 'hindi',
	'hmong': 'Hmong',
	'hungarian': 'húngaro',
	'iloko': 'Iloquín',
	'indonesian': 'indonesio',
	'kannada': 'Canarés',
	'khmer': 'Jemer',
	'korean': 'coreano',
	'lao': 'Laosiano',
	'malagasy': 'madagascarí',
	'malay': 'malayo',
	'malayalam': 'Malabar',
	'mandarin': 'mandarín',
	'marathi': 'Maratí',
	'nepali': 'Nepalí',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polaco',
	'portuguese': 'portugués',
	'punjabi': 'punjabi',
	'russian': 'ruso',
	'serbian': 'serbio',
	'sindhi': 'Sindhi',
	'spanish': 'Español',
	'swahili': 'swahili',
	'swedish': 'sueco',
	'tagalog': 'Tagalo',
	'tamil': 'Tamil',
	'telugu': 'Télugu',
	'thai': 'tailandés',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turco',
	'vietnamese': 'vietnamita',
	'urdu': 'Urdú',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Swahili': {
	'title1': 'Aleph pamoja na Beth na Alpha pamoja na Angela',
	'title2': 'Mratibu wa Kujifunza',
	'language': 'Lugha',
	'Learning program': 'Programu ya kujifunza',
	'timePerDay': 'Muda kwa siku',
	'copy': 'Nakili',
	'copied': 'Imenakiliwa',
	'print': 'Chapisha',
	'Aleph': 'Aleph pamoja na Beth',
	'Alpha': 'Alpha akiwa na Angela',
	'afrikaans': 'Kiafrikana',
	'albanian': 'Kialbeni',
	'amharic': 'Kiamhari',
	'arabic': 'Kiarabu',
	'assamese': 'Kiassamese',
	'bengali': 'Kibengali',
	'burmese': 'Kiburma',
	'cebuano': 'Cebuano',
	'croatian': 'Kikroeshia',
	'dutch': 'Kiholanzi',
	'english': 'Kiingereza',
	'farsi': 'Kiajemi',
	'finnish': 'Kifini',
	'french': 'Kifaransa',
	'fulfulde': 'Fulfulde',
	'german': 'Kijerumani',
	'greek': 'Kigiriki',
	'gujarati': 'Kigujarati',
	'hausa': 'Kihausa',
	'hebrew': 'Kiebrania',
	'hindi': 'Kihindi',
	'hmong': 'Hmong',
	'hungarian': 'Kihungaria',
	'iloko': 'Iloko',
	'indonesian': 'Kiindonesia',
	'kannada': 'Kikanada',
	'khmer': 'Khmer',
	'korean': 'Kikorea',
	'lao': 'Lao',
	'malagasy': 'Kimalagasi',
	'malay': 'Kimalei',
	'malayalam': 'Kimalayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Kinepali',
	'odia': 'Odia',
	'pashto': 'Kipashto',
	'polish': 'Kipolandi',
	'portuguese': 'Kireno',
	'punjabi': 'Kipunjabi',
	'russian': 'Kirusi',
	'serbian': 'Kiserbia',
	'sindhi': 'Kisindhi',
	'spanish': 'Kihispania',
	'swahili': 'kiswahili',
	'swedish': 'Kiswidi',
	'tagalog': 'Kitagalogi',
	'tamil': 'Kitamil',
	'telugu': 'Kitelugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Kituruki',
	'vietnamese': 'Kivietinamu',
	'urdu': 'Kiurdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Swedish': {
	'title1': 'Aleph med Beth och Alpha med Angela',
	'title2': 'Learning Scheduler',
	'language': 'Språk',
	'Learning program': 'Lärande program',
	'timePerDay': 'Tid per dag',
	'copy': 'Kopiera',
	'copied': 'Kopierade',
	'print': 'Skriva ut',
	'Aleph': 'Aleph med Beth',
	'Alpha': 'Alpha med Angela',
	'afrikaans': 'afrikaans',
	'albanian': 'albanska',
	'amharic': 'amhariska',
	'arabic': 'arabiska',
	'assamese': 'assamiska',
	'bengali': 'bengaliska',
	'burmese': 'burmesiska',
	'cebuano': 'Cebuano',
	'croatian': 'Kroatisk',
	'dutch': 'holländska',
	'english': 'engelska',
	'farsi': 'Farsi',
	'finnish': 'finska',
	'french': 'franska',
	'fulfulde': 'Fulfulde',
	'german': 'tyska',
	'greek': 'grekiska',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'hebreiska',
	'hindi': 'hindi',
	'hmong': 'Hmong',
	'hungarian': 'ungerska',
	'iloko': 'Iloko',
	'indonesian': 'indonesiska',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'koreanska',
	'lao': 'Lao',
	'malagasy': 'Madagaskar',
	'malay': 'malajiska',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'nepalesiska',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'polska',
	'portuguese': 'portugisiska',
	'punjabi': 'Punjabi',
	'russian': 'ryska',
	'serbian': 'serbiska',
	'sindhi': 'Sindhi',
	'spanish': 'spanska',
	'swahili': 'Swahili',
	'swedish': 'svenska',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'turkiska',
	'vietnamese': 'vietnamesiska',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Tagalog': {
	'title1': 'Si Aleph kasama si Beth at si Alpha kay Angela',
	'title2': 'Learning Scheduler',
	'language': 'Wika',
	'Learning program': 'Programa sa pag-aaral',
	'timePerDay': 'Oras bawat araw',
	'copy': 'Kopyahin',
	'copied': 'Kinopya',
	'print': 'Print',
	'Aleph': 'Si Aleph kasama si Beth',
	'Alpha': 'Alpha kasama si Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albaniano',
	'amharic': 'Amharic',
	'arabic': 'Arabic',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese',
	'cebuano': 'Cebuano',
	'croatian': 'Croatian',
	'dutch': 'Dutch',
	'english': 'Ingles',
	'farsi': 'Farsi',
	'finnish': 'Finnish',
	'french': 'Pranses',
	'fulfulde': 'Fulfulde',
	'german': 'Aleman',
	'greek': 'Griyego',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'Hebrew',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hungarian',
	'iloko': 'Iloko',
	'indonesian': 'Indonesian',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Koreano',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Polish',
	'portuguese': 'Portuges',
	'punjabi': 'Punjabi',
	'russian': 'Ruso',
	'serbian': 'Serbian',
	'sindhi': 'Sindhi',
	'spanish': 'Espanyol',
	'swahili': 'Swahili',
	'swedish': 'Swedish',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Turkish',
	'vietnamese': 'Vietnamese',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Tamil': {
	'title1': 'பெத்துடன் அலெஃப் மற்றும் ஏஞ்சலாவுடன் ஆல்பா',
	'title2': 'கற்றல் திட்டமிடுபவர்',
	'language': 'மொழி',
	'Learning program': 'கற்றல் திட்டம்',
	'timePerDay': 'ஒரு நாளைக்கு நேரம்',
	'copy': 'நகலெடு',
	'copied': 'நகலெடுக்கப்பட்டது',
	'print': 'அச்சு',
	'Aleph': 'பெத்துடன் அலெஃப்',
	'Alpha': 'ஏஞ்சலாவுடன் ஆல்பா',
	'afrikaans': 'ஆப்பிரிக்கான்ஸ்',
	'albanian': 'அல்பேனியன்',
	'amharic': 'அம்ஹாரிக்',
	'arabic': 'அரபு',
	'assamese': 'அசாமி',
	'bengali': 'வங்காளம்',
	'burmese': 'பர்மிஸ்',
	'cebuano': 'செபுவானோ',
	'croatian': 'குரோஷியன்',
	'dutch': 'டச்சு',
	'english': 'ஆங்கிலம்',
	'farsi': 'ஃபார்ஸி',
	'finnish': 'பின்னிஷ்',
	'french': 'ஃபிரெஞ்சு',
	'fulfulde': 'ஃபுல்ஃபுல்டே',
	'german': 'ஜெர்மன்',
	'greek': 'கிரேக்கம்',
	'gujarati': 'குஜராத்தி',
	'hausa': 'ஹௌசா',
	'hebrew': 'ஹீப்ரு',
	'hindi': 'இந்தி',
	'hmong': 'ஹ்மாங்',
	'hungarian': 'ஹங்கேரியன்',
	'iloko': 'இலோகோ',
	'indonesian': 'இந்தோனேசியன்',
	'kannada': 'கன்னடம்',
	'khmer': 'கெமர்',
	'korean': 'கொரியன்',
	'lao': 'லாவோ',
	'malagasy': 'மலகாஸி',
	'malay': 'மலாய்',
	'malayalam': 'மலையாளம்',
	'mandarin': 'மாண்டரின்',
	'marathi': 'மராத்தி',
	'nepali': 'நேபாளி',
	'odia': 'ஒடியா',
	'pashto': 'பாஷ்டோ',
	'polish': 'போலிஷ்',
	'portuguese': 'போர்ச்சுகீஸ்',
	'punjabi': 'பஞ்சாபி',
	'russian': 'ரஷ்யன்',
	'serbian': 'செர்பியன்',
	'sindhi': 'சிந்தி',
	'spanish': 'ஸ்பானிஷ்',
	'swahili': 'சுவாஹிலி',
	'swedish': 'ஸ்வீடிஷ்',
	'tagalog': 'டலாக்',
	'tamil': 'தமிழ்',
	'telugu': 'தெலுங்கு',
	'thai': 'தாய்',
	'tok pisin': 'டோக் பிசின்',
	'turkish': 'துருக்கியம்',
	'vietnamese': 'வியட்நாமிய',
	'urdu': 'உருது',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Telugu': {
	'title1': 'బెత్ తో అలెఫ్ మరియు ఏంజెలా తో ఆల్ఫా',
	'title2': 'లెర్నింగ్ షెడ్యూలర్',
	'language': 'భాష',
	'Learning program': 'అభ్యాస కార్యక్రమం',
	'timePerDay': 'రోజుకు సమయం',
	'copy': 'కాపీ చేయండి',
	'copied': 'కాపీ చేయబడింది',
	'print': 'ప్రింట్',
	'Aleph': 'బెత్ తో అలెఫ్',
	'Alpha': 'ఏంజెలాతో ఆల్ఫా',
	'afrikaans': 'ఆఫ్రికాన్స్',
	'albanian': 'అల్బేనియన్',
	'amharic': 'అమ్హారిక్',
	'arabic': 'అరబిక్',
	'assamese': 'అస్సామీలు',
	'bengali': 'బెంగాలీ',
	'burmese': 'బర్మీస్',
	'cebuano': 'సెబువానో',
	'croatian': 'క్రొయేషియన్',
	'dutch': 'డచ్',
	'english': 'ఇంగ్లీష్',
	'farsi': 'ఫార్సీ',
	'finnish': 'ఫిన్నిష్',
	'french': 'ఫ్రెంచ్',
	'fulfulde': 'ఫుల్ఫుల్డే',
	'german': 'జర్మన్',
	'greek': 'గ్రీకు',
	'gujarati': 'గుజరాతీ',
	'hausa': 'హౌసా',
	'hebrew': 'హిబ్రూ',
	'hindi': 'హిందీ',
	'hmong': 'హ్మోంగ్',
	'hungarian': 'హంగేరియన్',
	'iloko': 'ఇలోకో',
	'indonesian': 'ఇండోనేషియన్',
	'kannada': 'కన్నడ',
	'khmer': 'ఖ్మేర్',
	'korean': 'కొరియన్',
	'lao': 'లావో',
	'malagasy': 'మలగాసీ',
	'malay': 'మలయ్',
	'malayalam': 'మలయాళం',
	'mandarin': 'మాండరిన్',
	'marathi': 'మరాఠీ',
	'nepali': 'నేపాలీ',
	'odia': 'ఒడియా',
	'pashto': 'పాష్టో',
	'polish': 'పోలిష్',
	'portuguese': 'పోర్చుగీస్',
	'punjabi': 'పంజాబీ',
	'russian': 'రష్యన్',
	'serbian': 'సెర్బియన్',
	'sindhi': 'సింధీ',
	'spanish': 'స్పానిష్',
	'swahili': 'స్వాహిలి',
	'swedish': 'స్వీడిష్',
	'tagalog': 'తగలోగ్',
	'tamil': 'తమిళం',
	'telugu': 'తెలుగు',
	'thai': 'థాయ్',
	'tok pisin': 'టోక్ పిసిన్',
	'turkish': 'టర్కిష్',
	'vietnamese': 'వియత్నామీస్',
	'urdu': 'ఉర్దూ',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Thai': {
	'title1': 'อาเลฟกับเบธ และอัลฟ่ากับแองเจล่า',
	'title2': 'ตัวกำหนดตารางการเรียนรู้',
	'language': 'ภาษา',
	'Learning program': 'โปรแกรมการเรียนรู้',
	'timePerDay': 'เวลาต่อวัน',
	'copy': 'สำเนา',
	'copied': 'คัดลอกแล้ว',
	'print': 'พิมพ์',
	'Aleph': 'อาเลฟกับเบธ',
	'Alpha': 'อัลฟ่ากับแองเจล่า',
	'afrikaans': 'แอฟริกัน',
	'albanian': 'ชาวแอลเบเนีย',
	'amharic': 'อัมฮาริก',
	'arabic': 'ภาษาอาหรับ',
	'assamese': 'อัสสัม',
	'bengali': 'ภาษาเบงกาลี',
	'burmese': 'พม่า',
	'cebuano': 'ชาวเซบู',
	'croatian': 'ภาษาโครเอเชียน',
	'dutch': 'ดัตช์',
	'english': 'ภาษาอังกฤษ',
	'farsi': 'ภาษาเปอร์เซีย',
	'finnish': 'ฟินแลนด์',
	'french': 'ภาษาฝรั่งเศส',
	'fulfulde': 'ฟูลฟุลเด',
	'german': 'เยอรมัน',
	'greek': 'กรีก',
	'gujarati': 'คุชราต',
	'hausa': 'ฮาอูซา',
	'hebrew': 'ภาษาฮีบรู',
	'hindi': 'ภาษาฮินดี',
	'hmong': 'ชาวม้ง',
	'hungarian': 'ฮังการี',
	'iloko': 'อิโลโก',
	'indonesian': 'ชาวอินโดนีเซีย',
	'kannada': 'ภาษากันนาดา',
	'khmer': 'ภาษาเขมร',
	'korean': 'เกาหลี',
	'lao': 'ลาว',
	'malagasy': 'มาลากาซี',
	'malay': 'มลายู',
	'malayalam': 'มาลายาลัม',
	'mandarin': 'ภาษาจีนกลาง',
	'marathi': 'มาราฐี',
	'nepali': 'เนปาล',
	'odia': 'โอเดีย',
	'pashto': 'ปาทาน',
	'polish': 'ขัด',
	'portuguese': 'โปรตุเกส',
	'punjabi': 'ปัญจาบ',
	'russian': 'รัสเซีย',
	'serbian': 'เซอร์เบีย',
	'sindhi': 'สินธุ',
	'spanish': 'สเปน',
	'swahili': 'ภาษาสวาฮีลี',
	'swedish': 'สวีเดน',
	'tagalog': 'ภาษาตากาล็อก',
	'tamil': 'ทมิฬ',
	'telugu': 'เตลูกู',
	'thai': 'แบบไทย',
	'tok pisin': 'ต็อกพิซิน',
	'turkish': 'ภาษาตุรกี',
	'vietnamese': 'เวียดนาม',
	'urdu': 'อูรดู',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Tok Pisin': {
	'title1': 'Aleph wantaim Beth na Alpha wantaim Angela',
	'title2': 'Sedula bilong lainim samting',
	'language': 'Tok ples',
	'Learning program': 'Lening program',
	'timePerDay': 'Taim long wan wan de',
	'copy': 'Kopi',
	'copied': 'Ol i kopim',
	'print': 'Printim',
	'Aleph': 'Aleph wantaim Beth',
	'Alpha': 'Alpha wantaim Angela',
	'afrikaans': 'Afrikaans',
	'albanian': 'Albania',
	'amharic': 'Amharic',
	'arabic': 'Arabik',
	'assamese': 'Assamese',
	'bengali': 'Bengali',
	'burmese': 'Burmese',
	'cebuano': 'Cebuano',
	'croatian': 'Kroesia',
	'dutch': 'Dutch',
	'english': 'Tok Inglis',
	'farsi': 'Farsi',
	'finnish': 'Tok Finlan',
	'french': 'Frans',
	'fulfulde': 'Fulfulde',
	'german': 'tok Jeman',
	'greek': 'Grik',
	'gujarati': 'Gujarati',
	'hausa': 'Hausa',
	'hebrew': 'tok Hibru',
	'hindi': 'Hindi',
	'hmong': 'Hmong',
	'hungarian': 'Hangari',
	'iloko': 'Iloko',
	'indonesian': 'Indonesian',
	'kannada': 'Kannada',
	'khmer': 'Khmer',
	'korean': 'Korean',
	'lao': 'Lao',
	'malagasy': 'Malagasy',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandarin',
	'marathi': 'Marathi',
	'nepali': 'Nepali',
	'odia': 'Odia',
	'pashto': 'Pashto',
	'polish': 'Tok Polan',
	'portuguese': 'Tok Potugal',
	'punjabi': 'Punjabi',
	'russian': 'Rasia',
	'serbian': 'Serbian',
	'sindhi': 'Sindhi',
	'spanish': 'Spanish',
	'swahili': 'Swahili',
	'swedish': 'Swedish',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Thai',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Tok Turki',
	'vietnamese': 'Vietnamis',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Turkish': {
	'title1': 'Aleph Beth ile ve Alpha Angela ile',
	'title2': 'Öğrenme Planlayıcısı',
	'language': 'Dil',
	'Learning program': 'Öğrenme programı',
	'timePerDay': 'Günlük zaman',
	'copy': 'Kopyala',
	'copied': 'Kopyalandı',
	'print': 'Yazdır',
	'Aleph': 'Aleph Beth ile',
	'Alpha': 'Angela ile Alfa',
	'afrikaans': 'Afrikaans',
	'albanian': 'Arnavut',
	'amharic': 'Amharca',
	'arabic': 'Arapça',
	'assamese': 'Assamca',
	'bengali': 'Bengalce',
	'burmese': 'Birmanyalı',
	'cebuano': 'Sebuanca',
	'croatian': 'Hırvat',
	'dutch': 'Flemenkçe',
	'english': 'İngilizce',
	'farsi': 'Farsça',
	'finnish': 'Fince',
	'french': 'Fransızca',
	'fulfulde': 'Tamamlandı',
	'german': 'Almanca',
	'greek': 'Yunan',
	'gujarati': 'Guceratça',
	'hausa': 'Hausa',
	'hebrew': 'İbranice',
	'hindi': 'Hintçe',
	'hmong': 'Hmong',
	'hungarian': 'Macarca',
	'iloko': 'İloko',
	'indonesian': 'Endonezyaca',
	'kannada': 'Kannada',
	'khmer': 'Kmerce',
	'korean': 'Korece',
	'lao': 'Lao',
	'malagasy': 'Madagaskarlı',
	'malay': 'Malay',
	'malayalam': 'Malayalam',
	'mandarin': 'Mandalina',
	'marathi': 'Marathi',
	'nepali': 'Nepalce',
	'odia': 'Odia',
	'pashto': 'Peştuca',
	'polish': 'Lehçe',
	'portuguese': 'Portekizce',
	'punjabi': 'Pencapça',
	'russian': 'Rusça',
	'serbian': 'Sırpça',
	'sindhi': 'Sindhi',
	'spanish': 'İspanyol',
	'swahili': 'Svahili',
	'swedish': 'İsveççe',
	'tagalog': 'Tagalog',
	'tamil': 'Tamil',
	'telugu': 'Telugu',
	'thai': 'Tayca',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Türkçe',
	'vietnamese': 'Vietnam',
	'urdu': 'Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Vietnamese': {
	'title1': 'Aleph với Beth và Alpha với Angela',
	'title2': 'Lập lịch học tập',
	'language': 'Ngôn ngữ',
	'Learning program': 'Chương trình học tập',
	'timePerDay': 'Thời gian mỗi ngày',
	'copy': 'Sao chép',
	'copied': 'Đã sao chép',
	'print': 'In',
	'Aleph': 'Aleph với Beth',
	'Alpha': 'Alpha với Angela',
	'afrikaans': 'Tiếng Afrikaans',
	'albanian': 'Tiếng Albania',
	'amharic': 'Tiếng Amharic',
	'arabic': 'Tiếng Ả Rập',
	'assamese': 'Tiếng Assam',
	'bengali': 'Tiếng Bengal',
	'burmese': 'Miến Điện',
	'cebuano': 'Tiếng Cebuano',
	'croatian': 'Tiếng Croatia',
	'dutch': 'Tiếng Hà Lan',
	'english': 'Tiếng Anh',
	'farsi': 'Tiếng Ba Tư',
	'finnish': 'Phần Lan',
	'french': 'Tiếng Pháp',
	'fulfulde': 'Hoàn thành',
	'german': 'Tiếng Đức',
	'greek': 'Tiếng Hy Lạp',
	'gujarati': 'Tiếng Gujarat',
	'hausa': 'Tiếng Hausa',
	'hebrew': 'Tiếng Do Thái',
	'hindi': 'Tiếng Hin-ddi',
	'hmong': 'Người H\'Mông',
	'hungarian': 'Tiếng Hungary',
	'iloko': 'Iloko',
	'indonesian': 'Tiếng Indonesia',
	'kannada': 'Tiếng Kannada',
	'khmer': 'Tiếng Khmer',
	'korean': 'Hàn Quốc',
	'lao': 'Lào',
	'malagasy': 'Tiếng Malagasy',
	'malay': 'Tiếng Mã Lai',
	'malayalam': 'Tiếng Mã Lai',
	'mandarin': 'Tiếng Quan Thoại',
	'marathi': 'Tiếng Marathi',
	'nepali': 'Tiếng Nepal',
	'odia': 'Tiếng Odia',
	'pashto': 'Tiếng Pashto',
	'polish': 'Đánh bóng',
	'portuguese': 'Tiếng Bồ Đào Nha',
	'punjabi': 'Tiếng Punjab',
	'russian': 'Tiếng Nga',
	'serbian': 'Tiếng Serbia',
	'sindhi': 'Tiếng Sindhi',
	'spanish': 'Tiếng Tây Ban Nha',
	'swahili': 'Tiếng Swahili',
	'swedish': 'Tiếng Thụy Điển',
	'tagalog': 'Tiếng Tagalog',
	'tamil': 'Tiếng Tamil',
	'telugu': 'Tiếng Telugu',
	'thai': 'Thái Lan',
	'tok pisin': 'Tok Pisin',
	'turkish': 'Thổ Nhĩ Kỳ',
	'vietnamese': 'Tiếng Việt',
	'urdu': 'Tiếng Urdu',
	'direction': 'LTR',
	'font': 'Arial',
	},
'Urdu': {
	'title1': 'ایلف بیتھ کے ساتھ اور الفا انجیلا کے ساتھ',
	'title2': 'سیکھنے کا شیڈولر',
	'language': 'زبان',
	'Learning program': 'سیکھنے کا پروگرام',
	'timePerDay': 'فی دن وقت',
	'copy': 'کاپی',
	'copied': 'کاپی',
	'print': 'پرنٹ',
	'Aleph': 'بیت کے ساتھ ایلیف',
	'Alpha': 'انجیلا کے ساتھ الفا',
	'afrikaans': 'افریقی',
	'albanian': 'البانوی',
	'amharic': 'امہاری',
	'arabic': 'عربی',
	'assamese': 'آسامی',
	'bengali': 'بنگالی',
	'burmese': 'برمی',
	'cebuano': 'سیبوانو',
	'croatian': 'کروشین',
	'dutch': 'ڈچ',
	'english': 'انگریزی',
	'farsi': 'فارسی',
	'finnish': 'فنش',
	'french': 'فرانسیسی',
	'fulfulde': 'Fulfulde',
	'german': 'جرمن',
	'greek': 'یونانی',
	'gujarati': 'گجراتی',
	'hausa': 'ہاؤسا',
	'hebrew': 'عبرانی',
	'hindi': 'ہندی',
	'hmong': 'ہمونگ',
	'hungarian': 'ہنگری',
	'iloko': 'Iloko',
	'indonesian': 'انڈونیشین',
	'kannada': 'کنڑ',
	'khmer': 'خمیر',
	'korean': 'کورین',
	'lao': 'لاؤ',
	'malagasy': 'ملاگاسی',
	'malay': 'مالائی',
	'malayalam': 'ملیالم',
	'mandarin': 'مینڈارن',
	'marathi': 'مراٹھی',
	'nepali': 'نیپالی',
	'odia': 'اوڈیا',
	'pashto': 'پشتو',
	'polish': 'پولش',
	'portuguese': 'پرتگالی',
	'punjabi': 'پنجابی',
	'russian': 'روسی',
	'serbian': 'سربیائی',
	'sindhi': 'سندھی',
	'spanish': 'ہسپانوی',
	'swahili': 'سواحلی',
	'swedish': 'سویڈش',
	'tagalog': 'ٹیگالوگ',
	'tamil': 'تامل',
	'telugu': 'تیلگو',
	'thai': 'تھائی',
	'tok pisin': 'ٹوک پیسن',
	'turkish': 'ترکی',
	'vietnamese': 'ویتنامی',
	'urdu': 'اردو',
	'direction': 'RTL',
	'font': 'Arial',
	},
};
